
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ArItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ArItem
 * 
 */
export type ArItemModel = runtime.Types.Result.DefaultSelection<Prisma.$ArItemPayload>

export type AggregateArItem = {
  _count: ArItemCountAggregateOutputType | null
  _min: ArItemMinAggregateOutputType | null
  _max: ArItemMaxAggregateOutputType | null
}

export type ArItemMinAggregateOutputType = {
  id: string | null
  filename: string | null
  filepath: string | null
  hasAnimations: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ArItemMaxAggregateOutputType = {
  id: string | null
  filename: string | null
  filepath: string | null
  hasAnimations: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ArItemCountAggregateOutputType = {
  id: number
  filename: number
  filepath: number
  hasAnimations: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ArItemMinAggregateInputType = {
  id?: true
  filename?: true
  filepath?: true
  hasAnimations?: true
  createdAt?: true
  updatedAt?: true
}

export type ArItemMaxAggregateInputType = {
  id?: true
  filename?: true
  filepath?: true
  hasAnimations?: true
  createdAt?: true
  updatedAt?: true
}

export type ArItemCountAggregateInputType = {
  id?: true
  filename?: true
  filepath?: true
  hasAnimations?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ArItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ArItem to aggregate.
   */
  where?: Prisma.ArItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArItems to fetch.
   */
  orderBy?: Prisma.ArItemOrderByWithRelationInput | Prisma.ArItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ArItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ArItems
  **/
  _count?: true | ArItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ArItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ArItemMaxAggregateInputType
}

export type GetArItemAggregateType<T extends ArItemAggregateArgs> = {
      [P in keyof T & keyof AggregateArItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateArItem[P]>
    : Prisma.GetScalarType<T[P], AggregateArItem[P]>
}




export type ArItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArItemWhereInput
  orderBy?: Prisma.ArItemOrderByWithAggregationInput | Prisma.ArItemOrderByWithAggregationInput[]
  by: Prisma.ArItemScalarFieldEnum[] | Prisma.ArItemScalarFieldEnum
  having?: Prisma.ArItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ArItemCountAggregateInputType | true
  _min?: ArItemMinAggregateInputType
  _max?: ArItemMaxAggregateInputType
}

export type ArItemGroupByOutputType = {
  id: string
  filename: string
  filepath: string
  hasAnimations: boolean
  createdAt: Date
  updatedAt: Date
  _count: ArItemCountAggregateOutputType | null
  _min: ArItemMinAggregateOutputType | null
  _max: ArItemMaxAggregateOutputType | null
}

type GetArItemGroupByPayload<T extends ArItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ArItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ArItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ArItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ArItemGroupByOutputType[P]>
      }
    >
  >



export type ArItemWhereInput = {
  AND?: Prisma.ArItemWhereInput | Prisma.ArItemWhereInput[]
  OR?: Prisma.ArItemWhereInput[]
  NOT?: Prisma.ArItemWhereInput | Prisma.ArItemWhereInput[]
  id?: Prisma.StringFilter<"ArItem"> | string
  filename?: Prisma.StringFilter<"ArItem"> | string
  filepath?: Prisma.StringFilter<"ArItem"> | string
  hasAnimations?: Prisma.BoolFilter<"ArItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ArItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ArItem"> | Date | string
  steps?: Prisma.StepListRelationFilter
}

export type ArItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  filepath?: Prisma.SortOrder
  hasAnimations?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  steps?: Prisma.StepOrderByRelationAggregateInput
}

export type ArItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  filepath?: string
  AND?: Prisma.ArItemWhereInput | Prisma.ArItemWhereInput[]
  OR?: Prisma.ArItemWhereInput[]
  NOT?: Prisma.ArItemWhereInput | Prisma.ArItemWhereInput[]
  filename?: Prisma.StringFilter<"ArItem"> | string
  hasAnimations?: Prisma.BoolFilter<"ArItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ArItem"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ArItem"> | Date | string
  steps?: Prisma.StepListRelationFilter
}, "id" | "filepath">

export type ArItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  filepath?: Prisma.SortOrder
  hasAnimations?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ArItemCountOrderByAggregateInput
  _max?: Prisma.ArItemMaxOrderByAggregateInput
  _min?: Prisma.ArItemMinOrderByAggregateInput
}

export type ArItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.ArItemScalarWhereWithAggregatesInput | Prisma.ArItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.ArItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ArItemScalarWhereWithAggregatesInput | Prisma.ArItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ArItem"> | string
  filename?: Prisma.StringWithAggregatesFilter<"ArItem"> | string
  filepath?: Prisma.StringWithAggregatesFilter<"ArItem"> | string
  hasAnimations?: Prisma.BoolWithAggregatesFilter<"ArItem"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ArItem"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ArItem"> | Date | string
}

export type ArItemCreateInput = {
  id?: string
  filename: string
  filepath: string
  hasAnimations?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  steps?: Prisma.StepCreateNestedManyWithoutArItemInput
}

export type ArItemUncheckedCreateInput = {
  id?: string
  filename: string
  filepath: string
  hasAnimations?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  steps?: Prisma.StepUncheckedCreateNestedManyWithoutArItemInput
}

export type ArItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  filepath?: Prisma.StringFieldUpdateOperationsInput | string
  hasAnimations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  steps?: Prisma.StepUpdateManyWithoutArItemNestedInput
}

export type ArItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  filepath?: Prisma.StringFieldUpdateOperationsInput | string
  hasAnimations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  steps?: Prisma.StepUncheckedUpdateManyWithoutArItemNestedInput
}

export type ArItemCreateManyInput = {
  id?: string
  filename: string
  filepath: string
  hasAnimations?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  filepath?: Prisma.StringFieldUpdateOperationsInput | string
  hasAnimations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  filepath?: Prisma.StringFieldUpdateOperationsInput | string
  hasAnimations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  filepath?: Prisma.SortOrder
  hasAnimations?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ArItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  filepath?: Prisma.SortOrder
  hasAnimations?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ArItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  filename?: Prisma.SortOrder
  filepath?: Prisma.SortOrder
  hasAnimations?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ArItemNullableScalarRelationFilter = {
  is?: Prisma.ArItemWhereInput | null
  isNot?: Prisma.ArItemWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type ArItemCreateNestedOneWithoutStepsInput = {
  create?: Prisma.XOR<Prisma.ArItemCreateWithoutStepsInput, Prisma.ArItemUncheckedCreateWithoutStepsInput>
  connectOrCreate?: Prisma.ArItemCreateOrConnectWithoutStepsInput
  connect?: Prisma.ArItemWhereUniqueInput
}

export type ArItemUpdateOneWithoutStepsNestedInput = {
  create?: Prisma.XOR<Prisma.ArItemCreateWithoutStepsInput, Prisma.ArItemUncheckedCreateWithoutStepsInput>
  connectOrCreate?: Prisma.ArItemCreateOrConnectWithoutStepsInput
  upsert?: Prisma.ArItemUpsertWithoutStepsInput
  disconnect?: Prisma.ArItemWhereInput | boolean
  delete?: Prisma.ArItemWhereInput | boolean
  connect?: Prisma.ArItemWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ArItemUpdateToOneWithWhereWithoutStepsInput, Prisma.ArItemUpdateWithoutStepsInput>, Prisma.ArItemUncheckedUpdateWithoutStepsInput>
}

export type ArItemCreateWithoutStepsInput = {
  id?: string
  filename: string
  filepath: string
  hasAnimations?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArItemUncheckedCreateWithoutStepsInput = {
  id?: string
  filename: string
  filepath: string
  hasAnimations?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArItemCreateOrConnectWithoutStepsInput = {
  where: Prisma.ArItemWhereUniqueInput
  create: Prisma.XOR<Prisma.ArItemCreateWithoutStepsInput, Prisma.ArItemUncheckedCreateWithoutStepsInput>
}

export type ArItemUpsertWithoutStepsInput = {
  update: Prisma.XOR<Prisma.ArItemUpdateWithoutStepsInput, Prisma.ArItemUncheckedUpdateWithoutStepsInput>
  create: Prisma.XOR<Prisma.ArItemCreateWithoutStepsInput, Prisma.ArItemUncheckedCreateWithoutStepsInput>
  where?: Prisma.ArItemWhereInput
}

export type ArItemUpdateToOneWithWhereWithoutStepsInput = {
  where?: Prisma.ArItemWhereInput
  data: Prisma.XOR<Prisma.ArItemUpdateWithoutStepsInput, Prisma.ArItemUncheckedUpdateWithoutStepsInput>
}

export type ArItemUpdateWithoutStepsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  filepath?: Prisma.StringFieldUpdateOperationsInput | string
  hasAnimations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArItemUncheckedUpdateWithoutStepsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  filename?: Prisma.StringFieldUpdateOperationsInput | string
  filepath?: Prisma.StringFieldUpdateOperationsInput | string
  hasAnimations?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ArItemCountOutputType
 */

export type ArItemCountOutputType = {
  steps: number
}

export type ArItemCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  steps?: boolean | ArItemCountOutputTypeCountStepsArgs
}

/**
 * ArItemCountOutputType without action
 */
export type ArItemCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItemCountOutputType
   */
  select?: Prisma.ArItemCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ArItemCountOutputType without action
 */
export type ArItemCountOutputTypeCountStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StepWhereInput
}


export type ArItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  filename?: boolean
  filepath?: boolean
  hasAnimations?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  steps?: boolean | Prisma.ArItem$stepsArgs<ExtArgs>
  _count?: boolean | Prisma.ArItemCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["arItem"]>

export type ArItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  filename?: boolean
  filepath?: boolean
  hasAnimations?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["arItem"]>

export type ArItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  filename?: boolean
  filepath?: boolean
  hasAnimations?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["arItem"]>

export type ArItemSelectScalar = {
  id?: boolean
  filename?: boolean
  filepath?: boolean
  hasAnimations?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ArItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "filename" | "filepath" | "hasAnimations" | "createdAt" | "updatedAt", ExtArgs["result"]["arItem"]>
export type ArItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  steps?: boolean | Prisma.ArItem$stepsArgs<ExtArgs>
  _count?: boolean | Prisma.ArItemCountOutputTypeDefaultArgs<ExtArgs>
}
export type ArItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ArItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ArItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ArItem"
  objects: {
    steps: Prisma.$StepPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    filename: string
    filepath: string
    hasAnimations: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["arItem"]>
  composites: {}
}

export type ArItemGetPayload<S extends boolean | null | undefined | ArItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ArItemPayload, S>

export type ArItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ArItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ArItemCountAggregateInputType | true
  }

export interface ArItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ArItem'], meta: { name: 'ArItem' } }
  /**
   * Find zero or one ArItem that matches the filter.
   * @param {ArItemFindUniqueArgs} args - Arguments to find a ArItem
   * @example
   * // Get one ArItem
   * const arItem = await prisma.arItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ArItemFindUniqueArgs>(args: Prisma.SelectSubset<T, ArItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ArItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ArItemFindUniqueOrThrowArgs} args - Arguments to find a ArItem
   * @example
   * // Get one ArItem
   * const arItem = await prisma.arItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ArItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ArItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ArItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemFindFirstArgs} args - Arguments to find a ArItem
   * @example
   * // Get one ArItem
   * const arItem = await prisma.arItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ArItemFindFirstArgs>(args?: Prisma.SelectSubset<T, ArItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ArItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemFindFirstOrThrowArgs} args - Arguments to find a ArItem
   * @example
   * // Get one ArItem
   * const arItem = await prisma.arItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ArItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ArItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ArItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ArItems
   * const arItems = await prisma.arItem.findMany()
   * 
   * // Get first 10 ArItems
   * const arItems = await prisma.arItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const arItemWithIdOnly = await prisma.arItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ArItemFindManyArgs>(args?: Prisma.SelectSubset<T, ArItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ArItem.
   * @param {ArItemCreateArgs} args - Arguments to create a ArItem.
   * @example
   * // Create one ArItem
   * const ArItem = await prisma.arItem.create({
   *   data: {
   *     // ... data to create a ArItem
   *   }
   * })
   * 
   */
  create<T extends ArItemCreateArgs>(args: Prisma.SelectSubset<T, ArItemCreateArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ArItems.
   * @param {ArItemCreateManyArgs} args - Arguments to create many ArItems.
   * @example
   * // Create many ArItems
   * const arItem = await prisma.arItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ArItemCreateManyArgs>(args?: Prisma.SelectSubset<T, ArItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ArItems and returns the data saved in the database.
   * @param {ArItemCreateManyAndReturnArgs} args - Arguments to create many ArItems.
   * @example
   * // Create many ArItems
   * const arItem = await prisma.arItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ArItems and only return the `id`
   * const arItemWithIdOnly = await prisma.arItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ArItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ArItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ArItem.
   * @param {ArItemDeleteArgs} args - Arguments to delete one ArItem.
   * @example
   * // Delete one ArItem
   * const ArItem = await prisma.arItem.delete({
   *   where: {
   *     // ... filter to delete one ArItem
   *   }
   * })
   * 
   */
  delete<T extends ArItemDeleteArgs>(args: Prisma.SelectSubset<T, ArItemDeleteArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ArItem.
   * @param {ArItemUpdateArgs} args - Arguments to update one ArItem.
   * @example
   * // Update one ArItem
   * const arItem = await prisma.arItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ArItemUpdateArgs>(args: Prisma.SelectSubset<T, ArItemUpdateArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ArItems.
   * @param {ArItemDeleteManyArgs} args - Arguments to filter ArItems to delete.
   * @example
   * // Delete a few ArItems
   * const { count } = await prisma.arItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ArItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, ArItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ArItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ArItems
   * const arItem = await prisma.arItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ArItemUpdateManyArgs>(args: Prisma.SelectSubset<T, ArItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ArItems and returns the data updated in the database.
   * @param {ArItemUpdateManyAndReturnArgs} args - Arguments to update many ArItems.
   * @example
   * // Update many ArItems
   * const arItem = await prisma.arItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ArItems and only return the `id`
   * const arItemWithIdOnly = await prisma.arItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ArItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ArItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ArItem.
   * @param {ArItemUpsertArgs} args - Arguments to update or create a ArItem.
   * @example
   * // Update or create a ArItem
   * const arItem = await prisma.arItem.upsert({
   *   create: {
   *     // ... data to create a ArItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ArItem we want to update
   *   }
   * })
   */
  upsert<T extends ArItemUpsertArgs>(args: Prisma.SelectSubset<T, ArItemUpsertArgs<ExtArgs>>): Prisma.Prisma__ArItemClient<runtime.Types.Result.GetResult<Prisma.$ArItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ArItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemCountArgs} args - Arguments to filter ArItems to count.
   * @example
   * // Count the number of ArItems
   * const count = await prisma.arItem.count({
   *   where: {
   *     // ... the filter for the ArItems we want to count
   *   }
   * })
  **/
  count<T extends ArItemCountArgs>(
    args?: Prisma.Subset<T, ArItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ArItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ArItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ArItemAggregateArgs>(args: Prisma.Subset<T, ArItemAggregateArgs>): Prisma.PrismaPromise<GetArItemAggregateType<T>>

  /**
   * Group by ArItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ArItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ArItemGroupByArgs['orderBy'] }
      : { orderBy?: ArItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ArItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetArItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ArItem model
 */
readonly fields: ArItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ArItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ArItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  steps<T extends Prisma.ArItem$stepsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ArItem$stepsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ArItem model
 */
export interface ArItemFieldRefs {
  readonly id: Prisma.FieldRef<"ArItem", 'String'>
  readonly filename: Prisma.FieldRef<"ArItem", 'String'>
  readonly filepath: Prisma.FieldRef<"ArItem", 'String'>
  readonly hasAnimations: Prisma.FieldRef<"ArItem", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ArItem", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ArItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ArItem findUnique
 */
export type ArItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * Filter, which ArItem to fetch.
   */
  where: Prisma.ArItemWhereUniqueInput
}

/**
 * ArItem findUniqueOrThrow
 */
export type ArItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * Filter, which ArItem to fetch.
   */
  where: Prisma.ArItemWhereUniqueInput
}

/**
 * ArItem findFirst
 */
export type ArItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * Filter, which ArItem to fetch.
   */
  where?: Prisma.ArItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArItems to fetch.
   */
  orderBy?: Prisma.ArItemOrderByWithRelationInput | Prisma.ArItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ArItems.
   */
  cursor?: Prisma.ArItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArItems.
   */
  distinct?: Prisma.ArItemScalarFieldEnum | Prisma.ArItemScalarFieldEnum[]
}

/**
 * ArItem findFirstOrThrow
 */
export type ArItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * Filter, which ArItem to fetch.
   */
  where?: Prisma.ArItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArItems to fetch.
   */
  orderBy?: Prisma.ArItemOrderByWithRelationInput | Prisma.ArItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ArItems.
   */
  cursor?: Prisma.ArItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ArItems.
   */
  distinct?: Prisma.ArItemScalarFieldEnum | Prisma.ArItemScalarFieldEnum[]
}

/**
 * ArItem findMany
 */
export type ArItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * Filter, which ArItems to fetch.
   */
  where?: Prisma.ArItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ArItems to fetch.
   */
  orderBy?: Prisma.ArItemOrderByWithRelationInput | Prisma.ArItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ArItems.
   */
  cursor?: Prisma.ArItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ArItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ArItems.
   */
  skip?: number
  distinct?: Prisma.ArItemScalarFieldEnum | Prisma.ArItemScalarFieldEnum[]
}

/**
 * ArItem create
 */
export type ArItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * The data needed to create a ArItem.
   */
  data: Prisma.XOR<Prisma.ArItemCreateInput, Prisma.ArItemUncheckedCreateInput>
}

/**
 * ArItem createMany
 */
export type ArItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ArItems.
   */
  data: Prisma.ArItemCreateManyInput | Prisma.ArItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ArItem createManyAndReturn
 */
export type ArItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * The data used to create many ArItems.
   */
  data: Prisma.ArItemCreateManyInput | Prisma.ArItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ArItem update
 */
export type ArItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * The data needed to update a ArItem.
   */
  data: Prisma.XOR<Prisma.ArItemUpdateInput, Prisma.ArItemUncheckedUpdateInput>
  /**
   * Choose, which ArItem to update.
   */
  where: Prisma.ArItemWhereUniqueInput
}

/**
 * ArItem updateMany
 */
export type ArItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ArItems.
   */
  data: Prisma.XOR<Prisma.ArItemUpdateManyMutationInput, Prisma.ArItemUncheckedUpdateManyInput>
  /**
   * Filter which ArItems to update
   */
  where?: Prisma.ArItemWhereInput
  /**
   * Limit how many ArItems to update.
   */
  limit?: number
}

/**
 * ArItem updateManyAndReturn
 */
export type ArItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * The data used to update ArItems.
   */
  data: Prisma.XOR<Prisma.ArItemUpdateManyMutationInput, Prisma.ArItemUncheckedUpdateManyInput>
  /**
   * Filter which ArItems to update
   */
  where?: Prisma.ArItemWhereInput
  /**
   * Limit how many ArItems to update.
   */
  limit?: number
}

/**
 * ArItem upsert
 */
export type ArItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * The filter to search for the ArItem to update in case it exists.
   */
  where: Prisma.ArItemWhereUniqueInput
  /**
   * In case the ArItem found by the `where` argument doesn't exist, create a new ArItem with this data.
   */
  create: Prisma.XOR<Prisma.ArItemCreateInput, Prisma.ArItemUncheckedCreateInput>
  /**
   * In case the ArItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ArItemUpdateInput, Prisma.ArItemUncheckedUpdateInput>
}

/**
 * ArItem delete
 */
export type ArItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
  /**
   * Filter which ArItem to delete.
   */
  where: Prisma.ArItemWhereUniqueInput
}

/**
 * ArItem deleteMany
 */
export type ArItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ArItems to delete
   */
  where?: Prisma.ArItemWhereInput
  /**
   * Limit how many ArItems to delete.
   */
  limit?: number
}

/**
 * ArItem.steps
 */
export type ArItem$stepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Step
   */
  select?: Prisma.StepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Step
   */
  omit?: Prisma.StepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StepInclude<ExtArgs> | null
  where?: Prisma.StepWhereInput
  orderBy?: Prisma.StepOrderByWithRelationInput | Prisma.StepOrderByWithRelationInput[]
  cursor?: Prisma.StepWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StepScalarFieldEnum | Prisma.StepScalarFieldEnum[]
}

/**
 * ArItem without action
 */
export type ArItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ArItem
   */
  select?: Prisma.ArItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ArItem
   */
  omit?: Prisma.ArItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArItemInclude<ExtArgs> | null
}
