
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ClueUsage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ClueUsage
 * 
 */
export type ClueUsageModel = runtime.Types.Result.DefaultSelection<Prisma.$ClueUsagePayload>

export type AggregateClueUsage = {
  _count: ClueUsageCountAggregateOutputType | null
  _avg: ClueUsageAvgAggregateOutputType | null
  _sum: ClueUsageSumAggregateOutputType | null
  _min: ClueUsageMinAggregateOutputType | null
  _max: ClueUsageMaxAggregateOutputType | null
}

export type ClueUsageAvgAggregateOutputType = {
  id: number | null
  refProgress: number | null
  refClue: number | null
}

export type ClueUsageSumAggregateOutputType = {
  id: number | null
  refProgress: number | null
  refClue: number | null
}

export type ClueUsageMinAggregateOutputType = {
  id: number | null
  usedAt: Date | null
  refProgress: number | null
  refClue: number | null
}

export type ClueUsageMaxAggregateOutputType = {
  id: number | null
  usedAt: Date | null
  refProgress: number | null
  refClue: number | null
}

export type ClueUsageCountAggregateOutputType = {
  id: number
  usedAt: number
  refProgress: number
  refClue: number
  _all: number
}


export type ClueUsageAvgAggregateInputType = {
  id?: true
  refProgress?: true
  refClue?: true
}

export type ClueUsageSumAggregateInputType = {
  id?: true
  refProgress?: true
  refClue?: true
}

export type ClueUsageMinAggregateInputType = {
  id?: true
  usedAt?: true
  refProgress?: true
  refClue?: true
}

export type ClueUsageMaxAggregateInputType = {
  id?: true
  usedAt?: true
  refProgress?: true
  refClue?: true
}

export type ClueUsageCountAggregateInputType = {
  id?: true
  usedAt?: true
  refProgress?: true
  refClue?: true
  _all?: true
}

export type ClueUsageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClueUsage to aggregate.
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClueUsages to fetch.
   */
  orderBy?: Prisma.ClueUsageOrderByWithRelationInput | Prisma.ClueUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClueUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClueUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClueUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ClueUsages
  **/
  _count?: true | ClueUsageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClueUsageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClueUsageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClueUsageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClueUsageMaxAggregateInputType
}

export type GetClueUsageAggregateType<T extends ClueUsageAggregateArgs> = {
      [P in keyof T & keyof AggregateClueUsage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClueUsage[P]>
    : Prisma.GetScalarType<T[P], AggregateClueUsage[P]>
}




export type ClueUsageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClueUsageWhereInput
  orderBy?: Prisma.ClueUsageOrderByWithAggregationInput | Prisma.ClueUsageOrderByWithAggregationInput[]
  by: Prisma.ClueUsageScalarFieldEnum[] | Prisma.ClueUsageScalarFieldEnum
  having?: Prisma.ClueUsageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClueUsageCountAggregateInputType | true
  _avg?: ClueUsageAvgAggregateInputType
  _sum?: ClueUsageSumAggregateInputType
  _min?: ClueUsageMinAggregateInputType
  _max?: ClueUsageMaxAggregateInputType
}

export type ClueUsageGroupByOutputType = {
  id: number
  usedAt: Date
  refProgress: number
  refClue: number
  _count: ClueUsageCountAggregateOutputType | null
  _avg: ClueUsageAvgAggregateOutputType | null
  _sum: ClueUsageSumAggregateOutputType | null
  _min: ClueUsageMinAggregateOutputType | null
  _max: ClueUsageMaxAggregateOutputType | null
}

type GetClueUsageGroupByPayload<T extends ClueUsageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClueUsageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClueUsageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClueUsageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClueUsageGroupByOutputType[P]>
      }
    >
  >



export type ClueUsageWhereInput = {
  AND?: Prisma.ClueUsageWhereInput | Prisma.ClueUsageWhereInput[]
  OR?: Prisma.ClueUsageWhereInput[]
  NOT?: Prisma.ClueUsageWhereInput | Prisma.ClueUsageWhereInput[]
  id?: Prisma.IntFilter<"ClueUsage"> | number
  usedAt?: Prisma.DateTimeFilter<"ClueUsage"> | Date | string
  refProgress?: Prisma.IntFilter<"ClueUsage"> | number
  refClue?: Prisma.IntFilter<"ClueUsage"> | number
  progress?: Prisma.XOR<Prisma.ProgressScalarRelationFilter, Prisma.ProgressWhereInput>
  clue?: Prisma.XOR<Prisma.ClueScalarRelationFilter, Prisma.ClueWhereInput>
}

export type ClueUsageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
  progress?: Prisma.ProgressOrderByWithRelationInput
  clue?: Prisma.ClueOrderByWithRelationInput
}

export type ClueUsageWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  refProgress_refClue?: Prisma.ClueUsageRefProgressRefClueCompoundUniqueInput
  AND?: Prisma.ClueUsageWhereInput | Prisma.ClueUsageWhereInput[]
  OR?: Prisma.ClueUsageWhereInput[]
  NOT?: Prisma.ClueUsageWhereInput | Prisma.ClueUsageWhereInput[]
  usedAt?: Prisma.DateTimeFilter<"ClueUsage"> | Date | string
  refProgress?: Prisma.IntFilter<"ClueUsage"> | number
  refClue?: Prisma.IntFilter<"ClueUsage"> | number
  progress?: Prisma.XOR<Prisma.ProgressScalarRelationFilter, Prisma.ProgressWhereInput>
  clue?: Prisma.XOR<Prisma.ClueScalarRelationFilter, Prisma.ClueWhereInput>
}, "id" | "refProgress_refClue">

export type ClueUsageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
  _count?: Prisma.ClueUsageCountOrderByAggregateInput
  _avg?: Prisma.ClueUsageAvgOrderByAggregateInput
  _max?: Prisma.ClueUsageMaxOrderByAggregateInput
  _min?: Prisma.ClueUsageMinOrderByAggregateInput
  _sum?: Prisma.ClueUsageSumOrderByAggregateInput
}

export type ClueUsageScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClueUsageScalarWhereWithAggregatesInput | Prisma.ClueUsageScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClueUsageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClueUsageScalarWhereWithAggregatesInput | Prisma.ClueUsageScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ClueUsage"> | number
  usedAt?: Prisma.DateTimeWithAggregatesFilter<"ClueUsage"> | Date | string
  refProgress?: Prisma.IntWithAggregatesFilter<"ClueUsage"> | number
  refClue?: Prisma.IntWithAggregatesFilter<"ClueUsage"> | number
}

export type ClueUsageCreateInput = {
  usedAt?: Date | string
  progress: Prisma.ProgressCreateNestedOneWithoutClueUsagesInput
  clue: Prisma.ClueCreateNestedOneWithoutClueUsagesInput
}

export type ClueUsageUncheckedCreateInput = {
  id?: number
  usedAt?: Date | string
  refProgress: number
  refClue: number
}

export type ClueUsageUpdateInput = {
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  progress?: Prisma.ProgressUpdateOneRequiredWithoutClueUsagesNestedInput
  clue?: Prisma.ClueUpdateOneRequiredWithoutClueUsagesNestedInput
}

export type ClueUsageUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refProgress?: Prisma.IntFieldUpdateOperationsInput | number
  refClue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueUsageCreateManyInput = {
  id?: number
  usedAt?: Date | string
  refProgress: number
  refClue: number
}

export type ClueUsageUpdateManyMutationInput = {
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ClueUsageUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refProgress?: Prisma.IntFieldUpdateOperationsInput | number
  refClue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueUsageRefProgressRefClueCompoundUniqueInput = {
  refProgress: number
  refClue: number
}

export type ClueUsageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
}

export type ClueUsageAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
}

export type ClueUsageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
}

export type ClueUsageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  usedAt?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
}

export type ClueUsageSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  refProgress?: Prisma.SortOrder
  refClue?: Prisma.SortOrder
}

export type ClueUsageListRelationFilter = {
  every?: Prisma.ClueUsageWhereInput
  some?: Prisma.ClueUsageWhereInput
  none?: Prisma.ClueUsageWhereInput
}

export type ClueUsageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ClueUsageCreateNestedManyWithoutClueInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutClueInput, Prisma.ClueUsageUncheckedCreateWithoutClueInput> | Prisma.ClueUsageCreateWithoutClueInput[] | Prisma.ClueUsageUncheckedCreateWithoutClueInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutClueInput | Prisma.ClueUsageCreateOrConnectWithoutClueInput[]
  createMany?: Prisma.ClueUsageCreateManyClueInputEnvelope
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
}

export type ClueUsageUncheckedCreateNestedManyWithoutClueInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutClueInput, Prisma.ClueUsageUncheckedCreateWithoutClueInput> | Prisma.ClueUsageCreateWithoutClueInput[] | Prisma.ClueUsageUncheckedCreateWithoutClueInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutClueInput | Prisma.ClueUsageCreateOrConnectWithoutClueInput[]
  createMany?: Prisma.ClueUsageCreateManyClueInputEnvelope
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
}

export type ClueUsageUpdateManyWithoutClueNestedInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutClueInput, Prisma.ClueUsageUncheckedCreateWithoutClueInput> | Prisma.ClueUsageCreateWithoutClueInput[] | Prisma.ClueUsageUncheckedCreateWithoutClueInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutClueInput | Prisma.ClueUsageCreateOrConnectWithoutClueInput[]
  upsert?: Prisma.ClueUsageUpsertWithWhereUniqueWithoutClueInput | Prisma.ClueUsageUpsertWithWhereUniqueWithoutClueInput[]
  createMany?: Prisma.ClueUsageCreateManyClueInputEnvelope
  set?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  disconnect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  delete?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  update?: Prisma.ClueUsageUpdateWithWhereUniqueWithoutClueInput | Prisma.ClueUsageUpdateWithWhereUniqueWithoutClueInput[]
  updateMany?: Prisma.ClueUsageUpdateManyWithWhereWithoutClueInput | Prisma.ClueUsageUpdateManyWithWhereWithoutClueInput[]
  deleteMany?: Prisma.ClueUsageScalarWhereInput | Prisma.ClueUsageScalarWhereInput[]
}

export type ClueUsageUncheckedUpdateManyWithoutClueNestedInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutClueInput, Prisma.ClueUsageUncheckedCreateWithoutClueInput> | Prisma.ClueUsageCreateWithoutClueInput[] | Prisma.ClueUsageUncheckedCreateWithoutClueInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutClueInput | Prisma.ClueUsageCreateOrConnectWithoutClueInput[]
  upsert?: Prisma.ClueUsageUpsertWithWhereUniqueWithoutClueInput | Prisma.ClueUsageUpsertWithWhereUniqueWithoutClueInput[]
  createMany?: Prisma.ClueUsageCreateManyClueInputEnvelope
  set?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  disconnect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  delete?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  update?: Prisma.ClueUsageUpdateWithWhereUniqueWithoutClueInput | Prisma.ClueUsageUpdateWithWhereUniqueWithoutClueInput[]
  updateMany?: Prisma.ClueUsageUpdateManyWithWhereWithoutClueInput | Prisma.ClueUsageUpdateManyWithWhereWithoutClueInput[]
  deleteMany?: Prisma.ClueUsageScalarWhereInput | Prisma.ClueUsageScalarWhereInput[]
}

export type ClueUsageCreateNestedManyWithoutProgressInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutProgressInput, Prisma.ClueUsageUncheckedCreateWithoutProgressInput> | Prisma.ClueUsageCreateWithoutProgressInput[] | Prisma.ClueUsageUncheckedCreateWithoutProgressInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutProgressInput | Prisma.ClueUsageCreateOrConnectWithoutProgressInput[]
  createMany?: Prisma.ClueUsageCreateManyProgressInputEnvelope
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
}

export type ClueUsageUncheckedCreateNestedManyWithoutProgressInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutProgressInput, Prisma.ClueUsageUncheckedCreateWithoutProgressInput> | Prisma.ClueUsageCreateWithoutProgressInput[] | Prisma.ClueUsageUncheckedCreateWithoutProgressInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutProgressInput | Prisma.ClueUsageCreateOrConnectWithoutProgressInput[]
  createMany?: Prisma.ClueUsageCreateManyProgressInputEnvelope
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
}

export type ClueUsageUpdateManyWithoutProgressNestedInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutProgressInput, Prisma.ClueUsageUncheckedCreateWithoutProgressInput> | Prisma.ClueUsageCreateWithoutProgressInput[] | Prisma.ClueUsageUncheckedCreateWithoutProgressInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutProgressInput | Prisma.ClueUsageCreateOrConnectWithoutProgressInput[]
  upsert?: Prisma.ClueUsageUpsertWithWhereUniqueWithoutProgressInput | Prisma.ClueUsageUpsertWithWhereUniqueWithoutProgressInput[]
  createMany?: Prisma.ClueUsageCreateManyProgressInputEnvelope
  set?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  disconnect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  delete?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  update?: Prisma.ClueUsageUpdateWithWhereUniqueWithoutProgressInput | Prisma.ClueUsageUpdateWithWhereUniqueWithoutProgressInput[]
  updateMany?: Prisma.ClueUsageUpdateManyWithWhereWithoutProgressInput | Prisma.ClueUsageUpdateManyWithWhereWithoutProgressInput[]
  deleteMany?: Prisma.ClueUsageScalarWhereInput | Prisma.ClueUsageScalarWhereInput[]
}

export type ClueUsageUncheckedUpdateManyWithoutProgressNestedInput = {
  create?: Prisma.XOR<Prisma.ClueUsageCreateWithoutProgressInput, Prisma.ClueUsageUncheckedCreateWithoutProgressInput> | Prisma.ClueUsageCreateWithoutProgressInput[] | Prisma.ClueUsageUncheckedCreateWithoutProgressInput[]
  connectOrCreate?: Prisma.ClueUsageCreateOrConnectWithoutProgressInput | Prisma.ClueUsageCreateOrConnectWithoutProgressInput[]
  upsert?: Prisma.ClueUsageUpsertWithWhereUniqueWithoutProgressInput | Prisma.ClueUsageUpsertWithWhereUniqueWithoutProgressInput[]
  createMany?: Prisma.ClueUsageCreateManyProgressInputEnvelope
  set?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  disconnect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  delete?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  connect?: Prisma.ClueUsageWhereUniqueInput | Prisma.ClueUsageWhereUniqueInput[]
  update?: Prisma.ClueUsageUpdateWithWhereUniqueWithoutProgressInput | Prisma.ClueUsageUpdateWithWhereUniqueWithoutProgressInput[]
  updateMany?: Prisma.ClueUsageUpdateManyWithWhereWithoutProgressInput | Prisma.ClueUsageUpdateManyWithWhereWithoutProgressInput[]
  deleteMany?: Prisma.ClueUsageScalarWhereInput | Prisma.ClueUsageScalarWhereInput[]
}

export type ClueUsageCreateWithoutClueInput = {
  usedAt?: Date | string
  progress: Prisma.ProgressCreateNestedOneWithoutClueUsagesInput
}

export type ClueUsageUncheckedCreateWithoutClueInput = {
  id?: number
  usedAt?: Date | string
  refProgress: number
}

export type ClueUsageCreateOrConnectWithoutClueInput = {
  where: Prisma.ClueUsageWhereUniqueInput
  create: Prisma.XOR<Prisma.ClueUsageCreateWithoutClueInput, Prisma.ClueUsageUncheckedCreateWithoutClueInput>
}

export type ClueUsageCreateManyClueInputEnvelope = {
  data: Prisma.ClueUsageCreateManyClueInput | Prisma.ClueUsageCreateManyClueInput[]
  skipDuplicates?: boolean
}

export type ClueUsageUpsertWithWhereUniqueWithoutClueInput = {
  where: Prisma.ClueUsageWhereUniqueInput
  update: Prisma.XOR<Prisma.ClueUsageUpdateWithoutClueInput, Prisma.ClueUsageUncheckedUpdateWithoutClueInput>
  create: Prisma.XOR<Prisma.ClueUsageCreateWithoutClueInput, Prisma.ClueUsageUncheckedCreateWithoutClueInput>
}

export type ClueUsageUpdateWithWhereUniqueWithoutClueInput = {
  where: Prisma.ClueUsageWhereUniqueInput
  data: Prisma.XOR<Prisma.ClueUsageUpdateWithoutClueInput, Prisma.ClueUsageUncheckedUpdateWithoutClueInput>
}

export type ClueUsageUpdateManyWithWhereWithoutClueInput = {
  where: Prisma.ClueUsageScalarWhereInput
  data: Prisma.XOR<Prisma.ClueUsageUpdateManyMutationInput, Prisma.ClueUsageUncheckedUpdateManyWithoutClueInput>
}

export type ClueUsageScalarWhereInput = {
  AND?: Prisma.ClueUsageScalarWhereInput | Prisma.ClueUsageScalarWhereInput[]
  OR?: Prisma.ClueUsageScalarWhereInput[]
  NOT?: Prisma.ClueUsageScalarWhereInput | Prisma.ClueUsageScalarWhereInput[]
  id?: Prisma.IntFilter<"ClueUsage"> | number
  usedAt?: Prisma.DateTimeFilter<"ClueUsage"> | Date | string
  refProgress?: Prisma.IntFilter<"ClueUsage"> | number
  refClue?: Prisma.IntFilter<"ClueUsage"> | number
}

export type ClueUsageCreateWithoutProgressInput = {
  usedAt?: Date | string
  clue: Prisma.ClueCreateNestedOneWithoutClueUsagesInput
}

export type ClueUsageUncheckedCreateWithoutProgressInput = {
  id?: number
  usedAt?: Date | string
  refClue: number
}

export type ClueUsageCreateOrConnectWithoutProgressInput = {
  where: Prisma.ClueUsageWhereUniqueInput
  create: Prisma.XOR<Prisma.ClueUsageCreateWithoutProgressInput, Prisma.ClueUsageUncheckedCreateWithoutProgressInput>
}

export type ClueUsageCreateManyProgressInputEnvelope = {
  data: Prisma.ClueUsageCreateManyProgressInput | Prisma.ClueUsageCreateManyProgressInput[]
  skipDuplicates?: boolean
}

export type ClueUsageUpsertWithWhereUniqueWithoutProgressInput = {
  where: Prisma.ClueUsageWhereUniqueInput
  update: Prisma.XOR<Prisma.ClueUsageUpdateWithoutProgressInput, Prisma.ClueUsageUncheckedUpdateWithoutProgressInput>
  create: Prisma.XOR<Prisma.ClueUsageCreateWithoutProgressInput, Prisma.ClueUsageUncheckedCreateWithoutProgressInput>
}

export type ClueUsageUpdateWithWhereUniqueWithoutProgressInput = {
  where: Prisma.ClueUsageWhereUniqueInput
  data: Prisma.XOR<Prisma.ClueUsageUpdateWithoutProgressInput, Prisma.ClueUsageUncheckedUpdateWithoutProgressInput>
}

export type ClueUsageUpdateManyWithWhereWithoutProgressInput = {
  where: Prisma.ClueUsageScalarWhereInput
  data: Prisma.XOR<Prisma.ClueUsageUpdateManyMutationInput, Prisma.ClueUsageUncheckedUpdateManyWithoutProgressInput>
}

export type ClueUsageCreateManyClueInput = {
  id?: number
  usedAt?: Date | string
  refProgress: number
}

export type ClueUsageUpdateWithoutClueInput = {
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  progress?: Prisma.ProgressUpdateOneRequiredWithoutClueUsagesNestedInput
}

export type ClueUsageUncheckedUpdateWithoutClueInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refProgress?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueUsageUncheckedUpdateManyWithoutClueInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refProgress?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueUsageCreateManyProgressInput = {
  id?: number
  usedAt?: Date | string
  refClue: number
}

export type ClueUsageUpdateWithoutProgressInput = {
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clue?: Prisma.ClueUpdateOneRequiredWithoutClueUsagesNestedInput
}

export type ClueUsageUncheckedUpdateWithoutProgressInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refClue?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueUsageUncheckedUpdateManyWithoutProgressInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  usedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refClue?: Prisma.IntFieldUpdateOperationsInput | number
}



export type ClueUsageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usedAt?: boolean
  refProgress?: boolean
  refClue?: boolean
  progress?: boolean | Prisma.ProgressDefaultArgs<ExtArgs>
  clue?: boolean | Prisma.ClueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clueUsage"]>

export type ClueUsageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usedAt?: boolean
  refProgress?: boolean
  refClue?: boolean
  progress?: boolean | Prisma.ProgressDefaultArgs<ExtArgs>
  clue?: boolean | Prisma.ClueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clueUsage"]>

export type ClueUsageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  usedAt?: boolean
  refProgress?: boolean
  refClue?: boolean
  progress?: boolean | Prisma.ProgressDefaultArgs<ExtArgs>
  clue?: boolean | Prisma.ClueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clueUsage"]>

export type ClueUsageSelectScalar = {
  id?: boolean
  usedAt?: boolean
  refProgress?: boolean
  refClue?: boolean
}

export type ClueUsageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "usedAt" | "refProgress" | "refClue", ExtArgs["result"]["clueUsage"]>
export type ClueUsageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  progress?: boolean | Prisma.ProgressDefaultArgs<ExtArgs>
  clue?: boolean | Prisma.ClueDefaultArgs<ExtArgs>
}
export type ClueUsageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  progress?: boolean | Prisma.ProgressDefaultArgs<ExtArgs>
  clue?: boolean | Prisma.ClueDefaultArgs<ExtArgs>
}
export type ClueUsageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  progress?: boolean | Prisma.ProgressDefaultArgs<ExtArgs>
  clue?: boolean | Prisma.ClueDefaultArgs<ExtArgs>
}

export type $ClueUsagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ClueUsage"
  objects: {
    progress: Prisma.$ProgressPayload<ExtArgs>
    clue: Prisma.$CluePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    usedAt: Date
    refProgress: number
    refClue: number
  }, ExtArgs["result"]["clueUsage"]>
  composites: {}
}

export type ClueUsageGetPayload<S extends boolean | null | undefined | ClueUsageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload, S>

export type ClueUsageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClueUsageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClueUsageCountAggregateInputType | true
  }

export interface ClueUsageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ClueUsage'], meta: { name: 'ClueUsage' } }
  /**
   * Find zero or one ClueUsage that matches the filter.
   * @param {ClueUsageFindUniqueArgs} args - Arguments to find a ClueUsage
   * @example
   * // Get one ClueUsage
   * const clueUsage = await prisma.clueUsage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClueUsageFindUniqueArgs>(args: Prisma.SelectSubset<T, ClueUsageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ClueUsage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClueUsageFindUniqueOrThrowArgs} args - Arguments to find a ClueUsage
   * @example
   * // Get one ClueUsage
   * const clueUsage = await prisma.clueUsage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClueUsageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClueUsageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClueUsage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageFindFirstArgs} args - Arguments to find a ClueUsage
   * @example
   * // Get one ClueUsage
   * const clueUsage = await prisma.clueUsage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClueUsageFindFirstArgs>(args?: Prisma.SelectSubset<T, ClueUsageFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ClueUsage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageFindFirstOrThrowArgs} args - Arguments to find a ClueUsage
   * @example
   * // Get one ClueUsage
   * const clueUsage = await prisma.clueUsage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClueUsageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClueUsageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ClueUsages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ClueUsages
   * const clueUsages = await prisma.clueUsage.findMany()
   * 
   * // Get first 10 ClueUsages
   * const clueUsages = await prisma.clueUsage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clueUsageWithIdOnly = await prisma.clueUsage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClueUsageFindManyArgs>(args?: Prisma.SelectSubset<T, ClueUsageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ClueUsage.
   * @param {ClueUsageCreateArgs} args - Arguments to create a ClueUsage.
   * @example
   * // Create one ClueUsage
   * const ClueUsage = await prisma.clueUsage.create({
   *   data: {
   *     // ... data to create a ClueUsage
   *   }
   * })
   * 
   */
  create<T extends ClueUsageCreateArgs>(args: Prisma.SelectSubset<T, ClueUsageCreateArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ClueUsages.
   * @param {ClueUsageCreateManyArgs} args - Arguments to create many ClueUsages.
   * @example
   * // Create many ClueUsages
   * const clueUsage = await prisma.clueUsage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClueUsageCreateManyArgs>(args?: Prisma.SelectSubset<T, ClueUsageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ClueUsages and returns the data saved in the database.
   * @param {ClueUsageCreateManyAndReturnArgs} args - Arguments to create many ClueUsages.
   * @example
   * // Create many ClueUsages
   * const clueUsage = await prisma.clueUsage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ClueUsages and only return the `id`
   * const clueUsageWithIdOnly = await prisma.clueUsage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClueUsageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClueUsageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ClueUsage.
   * @param {ClueUsageDeleteArgs} args - Arguments to delete one ClueUsage.
   * @example
   * // Delete one ClueUsage
   * const ClueUsage = await prisma.clueUsage.delete({
   *   where: {
   *     // ... filter to delete one ClueUsage
   *   }
   * })
   * 
   */
  delete<T extends ClueUsageDeleteArgs>(args: Prisma.SelectSubset<T, ClueUsageDeleteArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ClueUsage.
   * @param {ClueUsageUpdateArgs} args - Arguments to update one ClueUsage.
   * @example
   * // Update one ClueUsage
   * const clueUsage = await prisma.clueUsage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClueUsageUpdateArgs>(args: Prisma.SelectSubset<T, ClueUsageUpdateArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ClueUsages.
   * @param {ClueUsageDeleteManyArgs} args - Arguments to filter ClueUsages to delete.
   * @example
   * // Delete a few ClueUsages
   * const { count } = await prisma.clueUsage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClueUsageDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClueUsageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClueUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ClueUsages
   * const clueUsage = await prisma.clueUsage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClueUsageUpdateManyArgs>(args: Prisma.SelectSubset<T, ClueUsageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ClueUsages and returns the data updated in the database.
   * @param {ClueUsageUpdateManyAndReturnArgs} args - Arguments to update many ClueUsages.
   * @example
   * // Update many ClueUsages
   * const clueUsage = await prisma.clueUsage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ClueUsages and only return the `id`
   * const clueUsageWithIdOnly = await prisma.clueUsage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClueUsageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClueUsageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ClueUsage.
   * @param {ClueUsageUpsertArgs} args - Arguments to update or create a ClueUsage.
   * @example
   * // Update or create a ClueUsage
   * const clueUsage = await prisma.clueUsage.upsert({
   *   create: {
   *     // ... data to create a ClueUsage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ClueUsage we want to update
   *   }
   * })
   */
  upsert<T extends ClueUsageUpsertArgs>(args: Prisma.SelectSubset<T, ClueUsageUpsertArgs<ExtArgs>>): Prisma.Prisma__ClueUsageClient<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ClueUsages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageCountArgs} args - Arguments to filter ClueUsages to count.
   * @example
   * // Count the number of ClueUsages
   * const count = await prisma.clueUsage.count({
   *   where: {
   *     // ... the filter for the ClueUsages we want to count
   *   }
   * })
  **/
  count<T extends ClueUsageCountArgs>(
    args?: Prisma.Subset<T, ClueUsageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClueUsageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ClueUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClueUsageAggregateArgs>(args: Prisma.Subset<T, ClueUsageAggregateArgs>): Prisma.PrismaPromise<GetClueUsageAggregateType<T>>

  /**
   * Group by ClueUsage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUsageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClueUsageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClueUsageGroupByArgs['orderBy'] }
      : { orderBy?: ClueUsageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClueUsageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClueUsageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ClueUsage model
 */
readonly fields: ClueUsageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ClueUsage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClueUsageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  progress<T extends Prisma.ProgressDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProgressDefaultArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  clue<T extends Prisma.ClueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClueDefaultArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ClueUsage model
 */
export interface ClueUsageFieldRefs {
  readonly id: Prisma.FieldRef<"ClueUsage", 'Int'>
  readonly usedAt: Prisma.FieldRef<"ClueUsage", 'DateTime'>
  readonly refProgress: Prisma.FieldRef<"ClueUsage", 'Int'>
  readonly refClue: Prisma.FieldRef<"ClueUsage", 'Int'>
}
    

// Custom InputTypes
/**
 * ClueUsage findUnique
 */
export type ClueUsageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * Filter, which ClueUsage to fetch.
   */
  where: Prisma.ClueUsageWhereUniqueInput
}

/**
 * ClueUsage findUniqueOrThrow
 */
export type ClueUsageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * Filter, which ClueUsage to fetch.
   */
  where: Prisma.ClueUsageWhereUniqueInput
}

/**
 * ClueUsage findFirst
 */
export type ClueUsageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * Filter, which ClueUsage to fetch.
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClueUsages to fetch.
   */
  orderBy?: Prisma.ClueUsageOrderByWithRelationInput | Prisma.ClueUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClueUsages.
   */
  cursor?: Prisma.ClueUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClueUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClueUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClueUsages.
   */
  distinct?: Prisma.ClueUsageScalarFieldEnum | Prisma.ClueUsageScalarFieldEnum[]
}

/**
 * ClueUsage findFirstOrThrow
 */
export type ClueUsageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * Filter, which ClueUsage to fetch.
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClueUsages to fetch.
   */
  orderBy?: Prisma.ClueUsageOrderByWithRelationInput | Prisma.ClueUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ClueUsages.
   */
  cursor?: Prisma.ClueUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClueUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClueUsages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ClueUsages.
   */
  distinct?: Prisma.ClueUsageScalarFieldEnum | Prisma.ClueUsageScalarFieldEnum[]
}

/**
 * ClueUsage findMany
 */
export type ClueUsageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * Filter, which ClueUsages to fetch.
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ClueUsages to fetch.
   */
  orderBy?: Prisma.ClueUsageOrderByWithRelationInput | Prisma.ClueUsageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ClueUsages.
   */
  cursor?: Prisma.ClueUsageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ClueUsages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ClueUsages.
   */
  skip?: number
  distinct?: Prisma.ClueUsageScalarFieldEnum | Prisma.ClueUsageScalarFieldEnum[]
}

/**
 * ClueUsage create
 */
export type ClueUsageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * The data needed to create a ClueUsage.
   */
  data: Prisma.XOR<Prisma.ClueUsageCreateInput, Prisma.ClueUsageUncheckedCreateInput>
}

/**
 * ClueUsage createMany
 */
export type ClueUsageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ClueUsages.
   */
  data: Prisma.ClueUsageCreateManyInput | Prisma.ClueUsageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ClueUsage createManyAndReturn
 */
export type ClueUsageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * The data used to create many ClueUsages.
   */
  data: Prisma.ClueUsageCreateManyInput | Prisma.ClueUsageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ClueUsage update
 */
export type ClueUsageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * The data needed to update a ClueUsage.
   */
  data: Prisma.XOR<Prisma.ClueUsageUpdateInput, Prisma.ClueUsageUncheckedUpdateInput>
  /**
   * Choose, which ClueUsage to update.
   */
  where: Prisma.ClueUsageWhereUniqueInput
}

/**
 * ClueUsage updateMany
 */
export type ClueUsageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ClueUsages.
   */
  data: Prisma.XOR<Prisma.ClueUsageUpdateManyMutationInput, Prisma.ClueUsageUncheckedUpdateManyInput>
  /**
   * Filter which ClueUsages to update
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * Limit how many ClueUsages to update.
   */
  limit?: number
}

/**
 * ClueUsage updateManyAndReturn
 */
export type ClueUsageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * The data used to update ClueUsages.
   */
  data: Prisma.XOR<Prisma.ClueUsageUpdateManyMutationInput, Prisma.ClueUsageUncheckedUpdateManyInput>
  /**
   * Filter which ClueUsages to update
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * Limit how many ClueUsages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ClueUsage upsert
 */
export type ClueUsageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * The filter to search for the ClueUsage to update in case it exists.
   */
  where: Prisma.ClueUsageWhereUniqueInput
  /**
   * In case the ClueUsage found by the `where` argument doesn't exist, create a new ClueUsage with this data.
   */
  create: Prisma.XOR<Prisma.ClueUsageCreateInput, Prisma.ClueUsageUncheckedCreateInput>
  /**
   * In case the ClueUsage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClueUsageUpdateInput, Prisma.ClueUsageUncheckedUpdateInput>
}

/**
 * ClueUsage delete
 */
export type ClueUsageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  /**
   * Filter which ClueUsage to delete.
   */
  where: Prisma.ClueUsageWhereUniqueInput
}

/**
 * ClueUsage deleteMany
 */
export type ClueUsageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ClueUsages to delete
   */
  where?: Prisma.ClueUsageWhereInput
  /**
   * Limit how many ClueUsages to delete.
   */
  limit?: number
}

/**
 * ClueUsage without action
 */
export type ClueUsageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
}
