
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Clue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Clue
 * 
 */
export type ClueModel = runtime.Types.Result.DefaultSelection<Prisma.$CluePayload>

export type AggregateClue = {
  _count: ClueCountAggregateOutputType | null
  _avg: ClueAvgAggregateOutputType | null
  _sum: ClueSumAggregateOutputType | null
  _min: ClueMinAggregateOutputType | null
  _max: ClueMaxAggregateOutputType | null
}

export type ClueAvgAggregateOutputType = {
  id: number | null
  penaltyCost: number | null
  orderNumber: number | null
  refStep: number | null
}

export type ClueSumAggregateOutputType = {
  id: number | null
  penaltyCost: number | null
  orderNumber: number | null
  refStep: number | null
}

export type ClueMinAggregateOutputType = {
  id: number | null
  message: string | null
  penaltyCost: number | null
  orderNumber: number | null
  createdAt: Date | null
  updatedAt: Date | null
  refStep: number | null
}

export type ClueMaxAggregateOutputType = {
  id: number | null
  message: string | null
  penaltyCost: number | null
  orderNumber: number | null
  createdAt: Date | null
  updatedAt: Date | null
  refStep: number | null
}

export type ClueCountAggregateOutputType = {
  id: number
  message: number
  penaltyCost: number
  orderNumber: number
  createdAt: number
  updatedAt: number
  refStep: number
  _all: number
}


export type ClueAvgAggregateInputType = {
  id?: true
  penaltyCost?: true
  orderNumber?: true
  refStep?: true
}

export type ClueSumAggregateInputType = {
  id?: true
  penaltyCost?: true
  orderNumber?: true
  refStep?: true
}

export type ClueMinAggregateInputType = {
  id?: true
  message?: true
  penaltyCost?: true
  orderNumber?: true
  createdAt?: true
  updatedAt?: true
  refStep?: true
}

export type ClueMaxAggregateInputType = {
  id?: true
  message?: true
  penaltyCost?: true
  orderNumber?: true
  createdAt?: true
  updatedAt?: true
  refStep?: true
}

export type ClueCountAggregateInputType = {
  id?: true
  message?: true
  penaltyCost?: true
  orderNumber?: true
  createdAt?: true
  updatedAt?: true
  refStep?: true
  _all?: true
}

export type ClueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clue to aggregate.
   */
  where?: Prisma.ClueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clues to fetch.
   */
  orderBy?: Prisma.ClueOrderByWithRelationInput | Prisma.ClueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Clues
  **/
  _count?: true | ClueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClueAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClueSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClueMaxAggregateInputType
}

export type GetClueAggregateType<T extends ClueAggregateArgs> = {
      [P in keyof T & keyof AggregateClue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClue[P]>
    : Prisma.GetScalarType<T[P], AggregateClue[P]>
}




export type ClueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClueWhereInput
  orderBy?: Prisma.ClueOrderByWithAggregationInput | Prisma.ClueOrderByWithAggregationInput[]
  by: Prisma.ClueScalarFieldEnum[] | Prisma.ClueScalarFieldEnum
  having?: Prisma.ClueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClueCountAggregateInputType | true
  _avg?: ClueAvgAggregateInputType
  _sum?: ClueSumAggregateInputType
  _min?: ClueMinAggregateInputType
  _max?: ClueMaxAggregateInputType
}

export type ClueGroupByOutputType = {
  id: number
  message: string
  penaltyCost: number
  orderNumber: number
  createdAt: Date
  updatedAt: Date
  refStep: number
  _count: ClueCountAggregateOutputType | null
  _avg: ClueAvgAggregateOutputType | null
  _sum: ClueSumAggregateOutputType | null
  _min: ClueMinAggregateOutputType | null
  _max: ClueMaxAggregateOutputType | null
}

type GetClueGroupByPayload<T extends ClueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClueGroupByOutputType[P]>
      }
    >
  >



export type ClueWhereInput = {
  AND?: Prisma.ClueWhereInput | Prisma.ClueWhereInput[]
  OR?: Prisma.ClueWhereInput[]
  NOT?: Prisma.ClueWhereInput | Prisma.ClueWhereInput[]
  id?: Prisma.IntFilter<"Clue"> | number
  message?: Prisma.StringFilter<"Clue"> | string
  penaltyCost?: Prisma.IntFilter<"Clue"> | number
  orderNumber?: Prisma.IntFilter<"Clue"> | number
  createdAt?: Prisma.DateTimeFilter<"Clue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Clue"> | Date | string
  refStep?: Prisma.IntFilter<"Clue"> | number
  step?: Prisma.XOR<Prisma.StepScalarRelationFilter, Prisma.StepWhereInput>
  clueUsages?: Prisma.ClueUsageListRelationFilter
}

export type ClueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
  step?: Prisma.StepOrderByWithRelationInput
  clueUsages?: Prisma.ClueUsageOrderByRelationAggregateInput
}

export type ClueWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  refStep_orderNumber?: Prisma.ClueRefStepOrderNumberCompoundUniqueInput
  AND?: Prisma.ClueWhereInput | Prisma.ClueWhereInput[]
  OR?: Prisma.ClueWhereInput[]
  NOT?: Prisma.ClueWhereInput | Prisma.ClueWhereInput[]
  message?: Prisma.StringFilter<"Clue"> | string
  penaltyCost?: Prisma.IntFilter<"Clue"> | number
  orderNumber?: Prisma.IntFilter<"Clue"> | number
  createdAt?: Prisma.DateTimeFilter<"Clue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Clue"> | Date | string
  refStep?: Prisma.IntFilter<"Clue"> | number
  step?: Prisma.XOR<Prisma.StepScalarRelationFilter, Prisma.StepWhereInput>
  clueUsages?: Prisma.ClueUsageListRelationFilter
}, "id" | "refStep_orderNumber">

export type ClueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
  _count?: Prisma.ClueCountOrderByAggregateInput
  _avg?: Prisma.ClueAvgOrderByAggregateInput
  _max?: Prisma.ClueMaxOrderByAggregateInput
  _min?: Prisma.ClueMinOrderByAggregateInput
  _sum?: Prisma.ClueSumOrderByAggregateInput
}

export type ClueScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClueScalarWhereWithAggregatesInput | Prisma.ClueScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClueScalarWhereWithAggregatesInput | Prisma.ClueScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Clue"> | number
  message?: Prisma.StringWithAggregatesFilter<"Clue"> | string
  penaltyCost?: Prisma.IntWithAggregatesFilter<"Clue"> | number
  orderNumber?: Prisma.IntWithAggregatesFilter<"Clue"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Clue"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Clue"> | Date | string
  refStep?: Prisma.IntWithAggregatesFilter<"Clue"> | number
}

export type ClueCreateInput = {
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  step: Prisma.StepCreateNestedOneWithoutCluesInput
  clueUsages?: Prisma.ClueUsageCreateNestedManyWithoutClueInput
}

export type ClueUncheckedCreateInput = {
  id?: number
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  refStep: number
  clueUsages?: Prisma.ClueUsageUncheckedCreateNestedManyWithoutClueInput
}

export type ClueUpdateInput = {
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  step?: Prisma.StepUpdateOneRequiredWithoutCluesNestedInput
  clueUsages?: Prisma.ClueUsageUpdateManyWithoutClueNestedInput
}

export type ClueUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
  clueUsages?: Prisma.ClueUsageUncheckedUpdateManyWithoutClueNestedInput
}

export type ClueCreateManyInput = {
  id?: number
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  refStep: number
}

export type ClueUpdateManyMutationInput = {
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ClueUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueScalarRelationFilter = {
  is?: Prisma.ClueWhereInput
  isNot?: Prisma.ClueWhereInput
}

export type ClueRefStepOrderNumberCompoundUniqueInput = {
  refStep: number
  orderNumber: number
}

export type ClueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ClueAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ClueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ClueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ClueSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  penaltyCost?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ClueListRelationFilter = {
  every?: Prisma.ClueWhereInput
  some?: Prisma.ClueWhereInput
  none?: Prisma.ClueWhereInput
}

export type ClueOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ClueCreateNestedOneWithoutClueUsagesInput = {
  create?: Prisma.XOR<Prisma.ClueCreateWithoutClueUsagesInput, Prisma.ClueUncheckedCreateWithoutClueUsagesInput>
  connectOrCreate?: Prisma.ClueCreateOrConnectWithoutClueUsagesInput
  connect?: Prisma.ClueWhereUniqueInput
}

export type ClueUpdateOneRequiredWithoutClueUsagesNestedInput = {
  create?: Prisma.XOR<Prisma.ClueCreateWithoutClueUsagesInput, Prisma.ClueUncheckedCreateWithoutClueUsagesInput>
  connectOrCreate?: Prisma.ClueCreateOrConnectWithoutClueUsagesInput
  upsert?: Prisma.ClueUpsertWithoutClueUsagesInput
  connect?: Prisma.ClueWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClueUpdateToOneWithWhereWithoutClueUsagesInput, Prisma.ClueUpdateWithoutClueUsagesInput>, Prisma.ClueUncheckedUpdateWithoutClueUsagesInput>
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type ClueCreateNestedManyWithoutStepInput = {
  create?: Prisma.XOR<Prisma.ClueCreateWithoutStepInput, Prisma.ClueUncheckedCreateWithoutStepInput> | Prisma.ClueCreateWithoutStepInput[] | Prisma.ClueUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ClueCreateOrConnectWithoutStepInput | Prisma.ClueCreateOrConnectWithoutStepInput[]
  createMany?: Prisma.ClueCreateManyStepInputEnvelope
  connect?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
}

export type ClueUncheckedCreateNestedManyWithoutStepInput = {
  create?: Prisma.XOR<Prisma.ClueCreateWithoutStepInput, Prisma.ClueUncheckedCreateWithoutStepInput> | Prisma.ClueCreateWithoutStepInput[] | Prisma.ClueUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ClueCreateOrConnectWithoutStepInput | Prisma.ClueCreateOrConnectWithoutStepInput[]
  createMany?: Prisma.ClueCreateManyStepInputEnvelope
  connect?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
}

export type ClueUpdateManyWithoutStepNestedInput = {
  create?: Prisma.XOR<Prisma.ClueCreateWithoutStepInput, Prisma.ClueUncheckedCreateWithoutStepInput> | Prisma.ClueCreateWithoutStepInput[] | Prisma.ClueUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ClueCreateOrConnectWithoutStepInput | Prisma.ClueCreateOrConnectWithoutStepInput[]
  upsert?: Prisma.ClueUpsertWithWhereUniqueWithoutStepInput | Prisma.ClueUpsertWithWhereUniqueWithoutStepInput[]
  createMany?: Prisma.ClueCreateManyStepInputEnvelope
  set?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  disconnect?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  delete?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  connect?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  update?: Prisma.ClueUpdateWithWhereUniqueWithoutStepInput | Prisma.ClueUpdateWithWhereUniqueWithoutStepInput[]
  updateMany?: Prisma.ClueUpdateManyWithWhereWithoutStepInput | Prisma.ClueUpdateManyWithWhereWithoutStepInput[]
  deleteMany?: Prisma.ClueScalarWhereInput | Prisma.ClueScalarWhereInput[]
}

export type ClueUncheckedUpdateManyWithoutStepNestedInput = {
  create?: Prisma.XOR<Prisma.ClueCreateWithoutStepInput, Prisma.ClueUncheckedCreateWithoutStepInput> | Prisma.ClueCreateWithoutStepInput[] | Prisma.ClueUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ClueCreateOrConnectWithoutStepInput | Prisma.ClueCreateOrConnectWithoutStepInput[]
  upsert?: Prisma.ClueUpsertWithWhereUniqueWithoutStepInput | Prisma.ClueUpsertWithWhereUniqueWithoutStepInput[]
  createMany?: Prisma.ClueCreateManyStepInputEnvelope
  set?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  disconnect?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  delete?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  connect?: Prisma.ClueWhereUniqueInput | Prisma.ClueWhereUniqueInput[]
  update?: Prisma.ClueUpdateWithWhereUniqueWithoutStepInput | Prisma.ClueUpdateWithWhereUniqueWithoutStepInput[]
  updateMany?: Prisma.ClueUpdateManyWithWhereWithoutStepInput | Prisma.ClueUpdateManyWithWhereWithoutStepInput[]
  deleteMany?: Prisma.ClueScalarWhereInput | Prisma.ClueScalarWhereInput[]
}

export type ClueCreateWithoutClueUsagesInput = {
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  step: Prisma.StepCreateNestedOneWithoutCluesInput
}

export type ClueUncheckedCreateWithoutClueUsagesInput = {
  id?: number
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  refStep: number
}

export type ClueCreateOrConnectWithoutClueUsagesInput = {
  where: Prisma.ClueWhereUniqueInput
  create: Prisma.XOR<Prisma.ClueCreateWithoutClueUsagesInput, Prisma.ClueUncheckedCreateWithoutClueUsagesInput>
}

export type ClueUpsertWithoutClueUsagesInput = {
  update: Prisma.XOR<Prisma.ClueUpdateWithoutClueUsagesInput, Prisma.ClueUncheckedUpdateWithoutClueUsagesInput>
  create: Prisma.XOR<Prisma.ClueCreateWithoutClueUsagesInput, Prisma.ClueUncheckedCreateWithoutClueUsagesInput>
  where?: Prisma.ClueWhereInput
}

export type ClueUpdateToOneWithWhereWithoutClueUsagesInput = {
  where?: Prisma.ClueWhereInput
  data: Prisma.XOR<Prisma.ClueUpdateWithoutClueUsagesInput, Prisma.ClueUncheckedUpdateWithoutClueUsagesInput>
}

export type ClueUpdateWithoutClueUsagesInput = {
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  step?: Prisma.StepUpdateOneRequiredWithoutCluesNestedInput
}

export type ClueUncheckedUpdateWithoutClueUsagesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ClueCreateWithoutStepInput = {
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  clueUsages?: Prisma.ClueUsageCreateNestedManyWithoutClueInput
}

export type ClueUncheckedCreateWithoutStepInput = {
  id?: number
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
  clueUsages?: Prisma.ClueUsageUncheckedCreateNestedManyWithoutClueInput
}

export type ClueCreateOrConnectWithoutStepInput = {
  where: Prisma.ClueWhereUniqueInput
  create: Prisma.XOR<Prisma.ClueCreateWithoutStepInput, Prisma.ClueUncheckedCreateWithoutStepInput>
}

export type ClueCreateManyStepInputEnvelope = {
  data: Prisma.ClueCreateManyStepInput | Prisma.ClueCreateManyStepInput[]
  skipDuplicates?: boolean
}

export type ClueUpsertWithWhereUniqueWithoutStepInput = {
  where: Prisma.ClueWhereUniqueInput
  update: Prisma.XOR<Prisma.ClueUpdateWithoutStepInput, Prisma.ClueUncheckedUpdateWithoutStepInput>
  create: Prisma.XOR<Prisma.ClueCreateWithoutStepInput, Prisma.ClueUncheckedCreateWithoutStepInput>
}

export type ClueUpdateWithWhereUniqueWithoutStepInput = {
  where: Prisma.ClueWhereUniqueInput
  data: Prisma.XOR<Prisma.ClueUpdateWithoutStepInput, Prisma.ClueUncheckedUpdateWithoutStepInput>
}

export type ClueUpdateManyWithWhereWithoutStepInput = {
  where: Prisma.ClueScalarWhereInput
  data: Prisma.XOR<Prisma.ClueUpdateManyMutationInput, Prisma.ClueUncheckedUpdateManyWithoutStepInput>
}

export type ClueScalarWhereInput = {
  AND?: Prisma.ClueScalarWhereInput | Prisma.ClueScalarWhereInput[]
  OR?: Prisma.ClueScalarWhereInput[]
  NOT?: Prisma.ClueScalarWhereInput | Prisma.ClueScalarWhereInput[]
  id?: Prisma.IntFilter<"Clue"> | number
  message?: Prisma.StringFilter<"Clue"> | string
  penaltyCost?: Prisma.IntFilter<"Clue"> | number
  orderNumber?: Prisma.IntFilter<"Clue"> | number
  createdAt?: Prisma.DateTimeFilter<"Clue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Clue"> | Date | string
  refStep?: Prisma.IntFilter<"Clue"> | number
}

export type ClueCreateManyStepInput = {
  id?: number
  message: string
  penaltyCost?: number
  orderNumber: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ClueUpdateWithoutStepInput = {
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clueUsages?: Prisma.ClueUsageUpdateManyWithoutClueNestedInput
}

export type ClueUncheckedUpdateWithoutStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clueUsages?: Prisma.ClueUsageUncheckedUpdateManyWithoutClueNestedInput
}

export type ClueUncheckedUpdateManyWithoutStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.StringFieldUpdateOperationsInput | string
  penaltyCost?: Prisma.IntFieldUpdateOperationsInput | number
  orderNumber?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ClueCountOutputType
 */

export type ClueCountOutputType = {
  clueUsages: number
}

export type ClueCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clueUsages?: boolean | ClueCountOutputTypeCountClueUsagesArgs
}

/**
 * ClueCountOutputType without action
 */
export type ClueCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueCountOutputType
   */
  select?: Prisma.ClueCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClueCountOutputType without action
 */
export type ClueCountOutputTypeCountClueUsagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClueUsageWhereInput
}


export type ClueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  penaltyCost?: boolean
  orderNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refStep?: boolean
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
  clueUsages?: boolean | Prisma.Clue$clueUsagesArgs<ExtArgs>
  _count?: boolean | Prisma.ClueCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clue"]>

export type ClueSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  penaltyCost?: boolean
  orderNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refStep?: boolean
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clue"]>

export type ClueSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  penaltyCost?: boolean
  orderNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refStep?: boolean
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clue"]>

export type ClueSelectScalar = {
  id?: boolean
  message?: boolean
  penaltyCost?: boolean
  orderNumber?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refStep?: boolean
}

export type ClueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "message" | "penaltyCost" | "orderNumber" | "createdAt" | "updatedAt" | "refStep", ExtArgs["result"]["clue"]>
export type ClueInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
  clueUsages?: boolean | Prisma.Clue$clueUsagesArgs<ExtArgs>
  _count?: boolean | Prisma.ClueCountOutputTypeDefaultArgs<ExtArgs>
}
export type ClueIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}
export type ClueIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}

export type $CluePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Clue"
  objects: {
    step: Prisma.$StepPayload<ExtArgs>
    clueUsages: Prisma.$ClueUsagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    message: string
    penaltyCost: number
    orderNumber: number
    createdAt: Date
    updatedAt: Date
    refStep: number
  }, ExtArgs["result"]["clue"]>
  composites: {}
}

export type ClueGetPayload<S extends boolean | null | undefined | ClueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CluePayload, S>

export type ClueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClueCountAggregateInputType | true
  }

export interface ClueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Clue'], meta: { name: 'Clue' } }
  /**
   * Find zero or one Clue that matches the filter.
   * @param {ClueFindUniqueArgs} args - Arguments to find a Clue
   * @example
   * // Get one Clue
   * const clue = await prisma.clue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClueFindUniqueArgs>(args: Prisma.SelectSubset<T, ClueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Clue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClueFindUniqueOrThrowArgs} args - Arguments to find a Clue
   * @example
   * // Get one Clue
   * const clue = await prisma.clue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueFindFirstArgs} args - Arguments to find a Clue
   * @example
   * // Get one Clue
   * const clue = await prisma.clue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClueFindFirstArgs>(args?: Prisma.SelectSubset<T, ClueFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueFindFirstOrThrowArgs} args - Arguments to find a Clue
   * @example
   * // Get one Clue
   * const clue = await prisma.clue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Clues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Clues
   * const clues = await prisma.clue.findMany()
   * 
   * // Get first 10 Clues
   * const clues = await prisma.clue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const clueWithIdOnly = await prisma.clue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ClueFindManyArgs>(args?: Prisma.SelectSubset<T, ClueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Clue.
   * @param {ClueCreateArgs} args - Arguments to create a Clue.
   * @example
   * // Create one Clue
   * const Clue = await prisma.clue.create({
   *   data: {
   *     // ... data to create a Clue
   *   }
   * })
   * 
   */
  create<T extends ClueCreateArgs>(args: Prisma.SelectSubset<T, ClueCreateArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Clues.
   * @param {ClueCreateManyArgs} args - Arguments to create many Clues.
   * @example
   * // Create many Clues
   * const clue = await prisma.clue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClueCreateManyArgs>(args?: Prisma.SelectSubset<T, ClueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Clues and returns the data saved in the database.
   * @param {ClueCreateManyAndReturnArgs} args - Arguments to create many Clues.
   * @example
   * // Create many Clues
   * const clue = await prisma.clue.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Clues and only return the `id`
   * const clueWithIdOnly = await prisma.clue.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClueCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClueCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Clue.
   * @param {ClueDeleteArgs} args - Arguments to delete one Clue.
   * @example
   * // Delete one Clue
   * const Clue = await prisma.clue.delete({
   *   where: {
   *     // ... filter to delete one Clue
   *   }
   * })
   * 
   */
  delete<T extends ClueDeleteArgs>(args: Prisma.SelectSubset<T, ClueDeleteArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Clue.
   * @param {ClueUpdateArgs} args - Arguments to update one Clue.
   * @example
   * // Update one Clue
   * const clue = await prisma.clue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClueUpdateArgs>(args: Prisma.SelectSubset<T, ClueUpdateArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Clues.
   * @param {ClueDeleteManyArgs} args - Arguments to filter Clues to delete.
   * @example
   * // Delete a few Clues
   * const { count } = await prisma.clue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClueDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Clues
   * const clue = await prisma.clue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClueUpdateManyArgs>(args: Prisma.SelectSubset<T, ClueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clues and returns the data updated in the database.
   * @param {ClueUpdateManyAndReturnArgs} args - Arguments to update many Clues.
   * @example
   * // Update many Clues
   * const clue = await prisma.clue.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Clues and only return the `id`
   * const clueWithIdOnly = await prisma.clue.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClueUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClueUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Clue.
   * @param {ClueUpsertArgs} args - Arguments to update or create a Clue.
   * @example
   * // Update or create a Clue
   * const clue = await prisma.clue.upsert({
   *   create: {
   *     // ... data to create a Clue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Clue we want to update
   *   }
   * })
   */
  upsert<T extends ClueUpsertArgs>(args: Prisma.SelectSubset<T, ClueUpsertArgs<ExtArgs>>): Prisma.Prisma__ClueClient<runtime.Types.Result.GetResult<Prisma.$CluePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Clues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueCountArgs} args - Arguments to filter Clues to count.
   * @example
   * // Count the number of Clues
   * const count = await prisma.clue.count({
   *   where: {
   *     // ... the filter for the Clues we want to count
   *   }
   * })
  **/
  count<T extends ClueCountArgs>(
    args?: Prisma.Subset<T, ClueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Clue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClueAggregateArgs>(args: Prisma.Subset<T, ClueAggregateArgs>): Prisma.PrismaPromise<GetClueAggregateType<T>>

  /**
   * Group by Clue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClueGroupByArgs['orderBy'] }
      : { orderBy?: ClueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Clue model
 */
readonly fields: ClueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Clue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  step<T extends Prisma.StepDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StepDefaultArgs<ExtArgs>>): Prisma.Prisma__StepClient<runtime.Types.Result.GetResult<Prisma.$StepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  clueUsages<T extends Prisma.Clue$clueUsagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Clue$clueUsagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Clue model
 */
export interface ClueFieldRefs {
  readonly id: Prisma.FieldRef<"Clue", 'Int'>
  readonly message: Prisma.FieldRef<"Clue", 'String'>
  readonly penaltyCost: Prisma.FieldRef<"Clue", 'Int'>
  readonly orderNumber: Prisma.FieldRef<"Clue", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Clue", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Clue", 'DateTime'>
  readonly refStep: Prisma.FieldRef<"Clue", 'Int'>
}
    

// Custom InputTypes
/**
 * Clue findUnique
 */
export type ClueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * Filter, which Clue to fetch.
   */
  where: Prisma.ClueWhereUniqueInput
}

/**
 * Clue findUniqueOrThrow
 */
export type ClueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * Filter, which Clue to fetch.
   */
  where: Prisma.ClueWhereUniqueInput
}

/**
 * Clue findFirst
 */
export type ClueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * Filter, which Clue to fetch.
   */
  where?: Prisma.ClueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clues to fetch.
   */
  orderBy?: Prisma.ClueOrderByWithRelationInput | Prisma.ClueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clues.
   */
  cursor?: Prisma.ClueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clues.
   */
  distinct?: Prisma.ClueScalarFieldEnum | Prisma.ClueScalarFieldEnum[]
}

/**
 * Clue findFirstOrThrow
 */
export type ClueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * Filter, which Clue to fetch.
   */
  where?: Prisma.ClueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clues to fetch.
   */
  orderBy?: Prisma.ClueOrderByWithRelationInput | Prisma.ClueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clues.
   */
  cursor?: Prisma.ClueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clues.
   */
  distinct?: Prisma.ClueScalarFieldEnum | Prisma.ClueScalarFieldEnum[]
}

/**
 * Clue findMany
 */
export type ClueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * Filter, which Clues to fetch.
   */
  where?: Prisma.ClueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clues to fetch.
   */
  orderBy?: Prisma.ClueOrderByWithRelationInput | Prisma.ClueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Clues.
   */
  cursor?: Prisma.ClueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clues.
   */
  skip?: number
  distinct?: Prisma.ClueScalarFieldEnum | Prisma.ClueScalarFieldEnum[]
}

/**
 * Clue create
 */
export type ClueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * The data needed to create a Clue.
   */
  data: Prisma.XOR<Prisma.ClueCreateInput, Prisma.ClueUncheckedCreateInput>
}

/**
 * Clue createMany
 */
export type ClueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Clues.
   */
  data: Prisma.ClueCreateManyInput | Prisma.ClueCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Clue createManyAndReturn
 */
export type ClueCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * The data used to create many Clues.
   */
  data: Prisma.ClueCreateManyInput | Prisma.ClueCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Clue update
 */
export type ClueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * The data needed to update a Clue.
   */
  data: Prisma.XOR<Prisma.ClueUpdateInput, Prisma.ClueUncheckedUpdateInput>
  /**
   * Choose, which Clue to update.
   */
  where: Prisma.ClueWhereUniqueInput
}

/**
 * Clue updateMany
 */
export type ClueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Clues.
   */
  data: Prisma.XOR<Prisma.ClueUpdateManyMutationInput, Prisma.ClueUncheckedUpdateManyInput>
  /**
   * Filter which Clues to update
   */
  where?: Prisma.ClueWhereInput
  /**
   * Limit how many Clues to update.
   */
  limit?: number
}

/**
 * Clue updateManyAndReturn
 */
export type ClueUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * The data used to update Clues.
   */
  data: Prisma.XOR<Prisma.ClueUpdateManyMutationInput, Prisma.ClueUncheckedUpdateManyInput>
  /**
   * Filter which Clues to update
   */
  where?: Prisma.ClueWhereInput
  /**
   * Limit how many Clues to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Clue upsert
 */
export type ClueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * The filter to search for the Clue to update in case it exists.
   */
  where: Prisma.ClueWhereUniqueInput
  /**
   * In case the Clue found by the `where` argument doesn't exist, create a new Clue with this data.
   */
  create: Prisma.XOR<Prisma.ClueCreateInput, Prisma.ClueUncheckedCreateInput>
  /**
   * In case the Clue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClueUpdateInput, Prisma.ClueUncheckedUpdateInput>
}

/**
 * Clue delete
 */
export type ClueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
  /**
   * Filter which Clue to delete.
   */
  where: Prisma.ClueWhereUniqueInput
}

/**
 * Clue deleteMany
 */
export type ClueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clues to delete
   */
  where?: Prisma.ClueWhereInput
  /**
   * Limit how many Clues to delete.
   */
  limit?: number
}

/**
 * Clue.clueUsages
 */
export type Clue$clueUsagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  where?: Prisma.ClueUsageWhereInput
  orderBy?: Prisma.ClueUsageOrderByWithRelationInput | Prisma.ClueUsageOrderByWithRelationInput[]
  cursor?: Prisma.ClueUsageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ClueUsageScalarFieldEnum | Prisma.ClueUsageScalarFieldEnum[]
}

/**
 * Clue without action
 */
export type ClueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clue
   */
  select?: Prisma.ClueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clue
   */
  omit?: Prisma.ClueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueInclude<ExtArgs> | null
}
