
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Hunt` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Hunt
 * 
 */
export type HuntModel = runtime.Types.Result.DefaultSelection<Prisma.$HuntPayload>

export type AggregateHunt = {
  _count: HuntCountAggregateOutputType | null
  _avg: HuntAvgAggregateOutputType | null
  _sum: HuntSumAggregateOutputType | null
  _min: HuntMinAggregateOutputType | null
  _max: HuntMaxAggregateOutputType | null
}

export type HuntAvgAggregateOutputType = {
  id: number | null
  radius: number | null
  refUser: number | null
}

export type HuntSumAggregateOutputType = {
  id: number | null
  radius: number | null
  refUser: number | null
}

export type HuntMinAggregateOutputType = {
  id: number | null
  title: string | null
  shortDescription: string | null
  description: string | null
  startDate: Date | null
  endDate: Date | null
  radius: number | null
  coverImage: string | null
  status: $Enums.HuntStatus | null
  rewardType: string | null
  rewardValue: string | null
  createdAt: Date | null
  updatedAt: Date | null
  refUser: number | null
}

export type HuntMaxAggregateOutputType = {
  id: number | null
  title: string | null
  shortDescription: string | null
  description: string | null
  startDate: Date | null
  endDate: Date | null
  radius: number | null
  coverImage: string | null
  status: $Enums.HuntStatus | null
  rewardType: string | null
  rewardValue: string | null
  createdAt: Date | null
  updatedAt: Date | null
  refUser: number | null
}

export type HuntCountAggregateOutputType = {
  id: number
  title: number
  shortDescription: number
  description: number
  startDate: number
  endDate: number
  radius: number
  coverImage: number
  status: number
  rewardType: number
  rewardValue: number
  createdAt: number
  updatedAt: number
  refUser: number
  _all: number
}


export type HuntAvgAggregateInputType = {
  id?: true
  radius?: true
  refUser?: true
}

export type HuntSumAggregateInputType = {
  id?: true
  radius?: true
  refUser?: true
}

export type HuntMinAggregateInputType = {
  id?: true
  title?: true
  shortDescription?: true
  description?: true
  startDate?: true
  endDate?: true
  radius?: true
  coverImage?: true
  status?: true
  rewardType?: true
  rewardValue?: true
  createdAt?: true
  updatedAt?: true
  refUser?: true
}

export type HuntMaxAggregateInputType = {
  id?: true
  title?: true
  shortDescription?: true
  description?: true
  startDate?: true
  endDate?: true
  radius?: true
  coverImage?: true
  status?: true
  rewardType?: true
  rewardValue?: true
  createdAt?: true
  updatedAt?: true
  refUser?: true
}

export type HuntCountAggregateInputType = {
  id?: true
  title?: true
  shortDescription?: true
  description?: true
  startDate?: true
  endDate?: true
  radius?: true
  coverImage?: true
  status?: true
  rewardType?: true
  rewardValue?: true
  createdAt?: true
  updatedAt?: true
  refUser?: true
  _all?: true
}

export type HuntAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hunt to aggregate.
   */
  where?: Prisma.HuntWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hunts to fetch.
   */
  orderBy?: Prisma.HuntOrderByWithRelationInput | Prisma.HuntOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HuntWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hunts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hunts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Hunts
  **/
  _count?: true | HuntCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HuntAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HuntSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HuntMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HuntMaxAggregateInputType
}

export type GetHuntAggregateType<T extends HuntAggregateArgs> = {
      [P in keyof T & keyof AggregateHunt]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHunt[P]>
    : Prisma.GetScalarType<T[P], AggregateHunt[P]>
}




export type HuntGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HuntWhereInput
  orderBy?: Prisma.HuntOrderByWithAggregationInput | Prisma.HuntOrderByWithAggregationInput[]
  by: Prisma.HuntScalarFieldEnum[] | Prisma.HuntScalarFieldEnum
  having?: Prisma.HuntScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HuntCountAggregateInputType | true
  _avg?: HuntAvgAggregateInputType
  _sum?: HuntSumAggregateInputType
  _min?: HuntMinAggregateInputType
  _max?: HuntMaxAggregateInputType
}

export type HuntGroupByOutputType = {
  id: number
  title: string
  shortDescription: string | null
  description: string | null
  startDate: Date | null
  endDate: Date | null
  radius: number
  coverImage: string | null
  status: $Enums.HuntStatus
  rewardType: string | null
  rewardValue: string | null
  createdAt: Date
  updatedAt: Date
  refUser: number
  _count: HuntCountAggregateOutputType | null
  _avg: HuntAvgAggregateOutputType | null
  _sum: HuntSumAggregateOutputType | null
  _min: HuntMinAggregateOutputType | null
  _max: HuntMaxAggregateOutputType | null
}

type GetHuntGroupByPayload<T extends HuntGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HuntGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HuntGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HuntGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HuntGroupByOutputType[P]>
      }
    >
  >



export type HuntWhereInput = {
  AND?: Prisma.HuntWhereInput | Prisma.HuntWhereInput[]
  OR?: Prisma.HuntWhereInput[]
  NOT?: Prisma.HuntWhereInput | Prisma.HuntWhereInput[]
  id?: Prisma.IntFilter<"Hunt"> | number
  title?: Prisma.StringFilter<"Hunt"> | string
  shortDescription?: Prisma.StringNullableFilter<"Hunt"> | string | null
  description?: Prisma.StringNullableFilter<"Hunt"> | string | null
  startDate?: Prisma.DateTimeNullableFilter<"Hunt"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"Hunt"> | Date | string | null
  radius?: Prisma.IntFilter<"Hunt"> | number
  coverImage?: Prisma.StringNullableFilter<"Hunt"> | string | null
  status?: Prisma.EnumHuntStatusFilter<"Hunt"> | $Enums.HuntStatus
  rewardType?: Prisma.StringNullableFilter<"Hunt"> | string | null
  rewardValue?: Prisma.StringNullableFilter<"Hunt"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Hunt"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hunt"> | Date | string
  refUser?: Prisma.IntFilter<"Hunt"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  steps?: Prisma.StepListRelationFilter
  participations?: Prisma.ParticipationListRelationFilter
}

export type HuntOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  shortDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  startDate?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  radius?: Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  rewardType?: Prisma.SortOrderInput | Prisma.SortOrder
  rewardValue?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  steps?: Prisma.StepOrderByRelationAggregateInput
  participations?: Prisma.ParticipationOrderByRelationAggregateInput
}

export type HuntWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.HuntWhereInput | Prisma.HuntWhereInput[]
  OR?: Prisma.HuntWhereInput[]
  NOT?: Prisma.HuntWhereInput | Prisma.HuntWhereInput[]
  title?: Prisma.StringFilter<"Hunt"> | string
  shortDescription?: Prisma.StringNullableFilter<"Hunt"> | string | null
  description?: Prisma.StringNullableFilter<"Hunt"> | string | null
  startDate?: Prisma.DateTimeNullableFilter<"Hunt"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"Hunt"> | Date | string | null
  radius?: Prisma.IntFilter<"Hunt"> | number
  coverImage?: Prisma.StringNullableFilter<"Hunt"> | string | null
  status?: Prisma.EnumHuntStatusFilter<"Hunt"> | $Enums.HuntStatus
  rewardType?: Prisma.StringNullableFilter<"Hunt"> | string | null
  rewardValue?: Prisma.StringNullableFilter<"Hunt"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Hunt"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hunt"> | Date | string
  refUser?: Prisma.IntFilter<"Hunt"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  steps?: Prisma.StepListRelationFilter
  participations?: Prisma.ParticipationListRelationFilter
}, "id">

export type HuntOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  shortDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  startDate?: Prisma.SortOrderInput | Prisma.SortOrder
  endDate?: Prisma.SortOrderInput | Prisma.SortOrder
  radius?: Prisma.SortOrder
  coverImage?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  rewardType?: Prisma.SortOrderInput | Prisma.SortOrder
  rewardValue?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
  _count?: Prisma.HuntCountOrderByAggregateInput
  _avg?: Prisma.HuntAvgOrderByAggregateInput
  _max?: Prisma.HuntMaxOrderByAggregateInput
  _min?: Prisma.HuntMinOrderByAggregateInput
  _sum?: Prisma.HuntSumOrderByAggregateInput
}

export type HuntScalarWhereWithAggregatesInput = {
  AND?: Prisma.HuntScalarWhereWithAggregatesInput | Prisma.HuntScalarWhereWithAggregatesInput[]
  OR?: Prisma.HuntScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HuntScalarWhereWithAggregatesInput | Prisma.HuntScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Hunt"> | number
  title?: Prisma.StringWithAggregatesFilter<"Hunt"> | string
  shortDescription?: Prisma.StringNullableWithAggregatesFilter<"Hunt"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Hunt"> | string | null
  startDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Hunt"> | Date | string | null
  endDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Hunt"> | Date | string | null
  radius?: Prisma.IntWithAggregatesFilter<"Hunt"> | number
  coverImage?: Prisma.StringNullableWithAggregatesFilter<"Hunt"> | string | null
  status?: Prisma.EnumHuntStatusWithAggregatesFilter<"Hunt"> | $Enums.HuntStatus
  rewardType?: Prisma.StringNullableWithAggregatesFilter<"Hunt"> | string | null
  rewardValue?: Prisma.StringNullableWithAggregatesFilter<"Hunt"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Hunt"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Hunt"> | Date | string
  refUser?: Prisma.IntWithAggregatesFilter<"Hunt"> | number
}

export type HuntCreateInput = {
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutHuntsInput
  steps?: Prisma.StepCreateNestedManyWithoutHuntInput
  participations?: Prisma.ParticipationCreateNestedManyWithoutHuntInput
}

export type HuntUncheckedCreateInput = {
  id?: number
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refUser: number
  steps?: Prisma.StepUncheckedCreateNestedManyWithoutHuntInput
  participations?: Prisma.ParticipationUncheckedCreateNestedManyWithoutHuntInput
}

export type HuntUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutHuntsNestedInput
  steps?: Prisma.StepUpdateManyWithoutHuntNestedInput
  participations?: Prisma.ParticipationUpdateManyWithoutHuntNestedInput
}

export type HuntUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refUser?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.StepUncheckedUpdateManyWithoutHuntNestedInput
  participations?: Prisma.ParticipationUncheckedUpdateManyWithoutHuntNestedInput
}

export type HuntCreateManyInput = {
  id?: number
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refUser: number
}

export type HuntUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HuntUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refUser?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HuntCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  shortDescription?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  radius?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rewardType?: Prisma.SortOrder
  rewardValue?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
}

export type HuntAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  radius?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
}

export type HuntMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  shortDescription?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  radius?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rewardType?: Prisma.SortOrder
  rewardValue?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
}

export type HuntMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  shortDescription?: Prisma.SortOrder
  description?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  radius?: Prisma.SortOrder
  coverImage?: Prisma.SortOrder
  status?: Prisma.SortOrder
  rewardType?: Prisma.SortOrder
  rewardValue?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
}

export type HuntSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  radius?: Prisma.SortOrder
  refUser?: Prisma.SortOrder
}

export type HuntScalarRelationFilter = {
  is?: Prisma.HuntWhereInput
  isNot?: Prisma.HuntWhereInput
}

export type HuntListRelationFilter = {
  every?: Prisma.HuntWhereInput
  some?: Prisma.HuntWhereInput
  none?: Prisma.HuntWhereInput
}

export type HuntOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumHuntStatusFieldUpdateOperationsInput = {
  set?: $Enums.HuntStatus
}

export type HuntCreateNestedOneWithoutParticipationsInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutParticipationsInput, Prisma.HuntUncheckedCreateWithoutParticipationsInput>
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutParticipationsInput
  connect?: Prisma.HuntWhereUniqueInput
}

export type HuntUpdateOneRequiredWithoutParticipationsNestedInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutParticipationsInput, Prisma.HuntUncheckedCreateWithoutParticipationsInput>
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutParticipationsInput
  upsert?: Prisma.HuntUpsertWithoutParticipationsInput
  connect?: Prisma.HuntWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HuntUpdateToOneWithWhereWithoutParticipationsInput, Prisma.HuntUpdateWithoutParticipationsInput>, Prisma.HuntUncheckedUpdateWithoutParticipationsInput>
}

export type HuntCreateNestedOneWithoutStepsInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutStepsInput, Prisma.HuntUncheckedCreateWithoutStepsInput>
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutStepsInput
  connect?: Prisma.HuntWhereUniqueInput
}

export type HuntUpdateOneRequiredWithoutStepsNestedInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutStepsInput, Prisma.HuntUncheckedCreateWithoutStepsInput>
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutStepsInput
  upsert?: Prisma.HuntUpsertWithoutStepsInput
  connect?: Prisma.HuntWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HuntUpdateToOneWithWhereWithoutStepsInput, Prisma.HuntUpdateWithoutStepsInput>, Prisma.HuntUncheckedUpdateWithoutStepsInput>
}

export type HuntCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutUserInput, Prisma.HuntUncheckedCreateWithoutUserInput> | Prisma.HuntCreateWithoutUserInput[] | Prisma.HuntUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutUserInput | Prisma.HuntCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.HuntCreateManyUserInputEnvelope
  connect?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
}

export type HuntUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutUserInput, Prisma.HuntUncheckedCreateWithoutUserInput> | Prisma.HuntCreateWithoutUserInput[] | Prisma.HuntUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutUserInput | Prisma.HuntCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.HuntCreateManyUserInputEnvelope
  connect?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
}

export type HuntUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutUserInput, Prisma.HuntUncheckedCreateWithoutUserInput> | Prisma.HuntCreateWithoutUserInput[] | Prisma.HuntUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutUserInput | Prisma.HuntCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.HuntUpsertWithWhereUniqueWithoutUserInput | Prisma.HuntUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.HuntCreateManyUserInputEnvelope
  set?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  disconnect?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  delete?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  connect?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  update?: Prisma.HuntUpdateWithWhereUniqueWithoutUserInput | Prisma.HuntUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.HuntUpdateManyWithWhereWithoutUserInput | Prisma.HuntUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.HuntScalarWhereInput | Prisma.HuntScalarWhereInput[]
}

export type HuntUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.HuntCreateWithoutUserInput, Prisma.HuntUncheckedCreateWithoutUserInput> | Prisma.HuntCreateWithoutUserInput[] | Prisma.HuntUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HuntCreateOrConnectWithoutUserInput | Prisma.HuntCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.HuntUpsertWithWhereUniqueWithoutUserInput | Prisma.HuntUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.HuntCreateManyUserInputEnvelope
  set?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  disconnect?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  delete?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  connect?: Prisma.HuntWhereUniqueInput | Prisma.HuntWhereUniqueInput[]
  update?: Prisma.HuntUpdateWithWhereUniqueWithoutUserInput | Prisma.HuntUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.HuntUpdateManyWithWhereWithoutUserInput | Prisma.HuntUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.HuntScalarWhereInput | Prisma.HuntScalarWhereInput[]
}

export type HuntCreateWithoutParticipationsInput = {
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutHuntsInput
  steps?: Prisma.StepCreateNestedManyWithoutHuntInput
}

export type HuntUncheckedCreateWithoutParticipationsInput = {
  id?: number
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refUser: number
  steps?: Prisma.StepUncheckedCreateNestedManyWithoutHuntInput
}

export type HuntCreateOrConnectWithoutParticipationsInput = {
  where: Prisma.HuntWhereUniqueInput
  create: Prisma.XOR<Prisma.HuntCreateWithoutParticipationsInput, Prisma.HuntUncheckedCreateWithoutParticipationsInput>
}

export type HuntUpsertWithoutParticipationsInput = {
  update: Prisma.XOR<Prisma.HuntUpdateWithoutParticipationsInput, Prisma.HuntUncheckedUpdateWithoutParticipationsInput>
  create: Prisma.XOR<Prisma.HuntCreateWithoutParticipationsInput, Prisma.HuntUncheckedCreateWithoutParticipationsInput>
  where?: Prisma.HuntWhereInput
}

export type HuntUpdateToOneWithWhereWithoutParticipationsInput = {
  where?: Prisma.HuntWhereInput
  data: Prisma.XOR<Prisma.HuntUpdateWithoutParticipationsInput, Prisma.HuntUncheckedUpdateWithoutParticipationsInput>
}

export type HuntUpdateWithoutParticipationsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutHuntsNestedInput
  steps?: Prisma.StepUpdateManyWithoutHuntNestedInput
}

export type HuntUncheckedUpdateWithoutParticipationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refUser?: Prisma.IntFieldUpdateOperationsInput | number
  steps?: Prisma.StepUncheckedUpdateManyWithoutHuntNestedInput
}

export type HuntCreateWithoutStepsInput = {
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutHuntsInput
  participations?: Prisma.ParticipationCreateNestedManyWithoutHuntInput
}

export type HuntUncheckedCreateWithoutStepsInput = {
  id?: number
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refUser: number
  participations?: Prisma.ParticipationUncheckedCreateNestedManyWithoutHuntInput
}

export type HuntCreateOrConnectWithoutStepsInput = {
  where: Prisma.HuntWhereUniqueInput
  create: Prisma.XOR<Prisma.HuntCreateWithoutStepsInput, Prisma.HuntUncheckedCreateWithoutStepsInput>
}

export type HuntUpsertWithoutStepsInput = {
  update: Prisma.XOR<Prisma.HuntUpdateWithoutStepsInput, Prisma.HuntUncheckedUpdateWithoutStepsInput>
  create: Prisma.XOR<Prisma.HuntCreateWithoutStepsInput, Prisma.HuntUncheckedCreateWithoutStepsInput>
  where?: Prisma.HuntWhereInput
}

export type HuntUpdateToOneWithWhereWithoutStepsInput = {
  where?: Prisma.HuntWhereInput
  data: Prisma.XOR<Prisma.HuntUpdateWithoutStepsInput, Prisma.HuntUncheckedUpdateWithoutStepsInput>
}

export type HuntUpdateWithoutStepsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutHuntsNestedInput
  participations?: Prisma.ParticipationUpdateManyWithoutHuntNestedInput
}

export type HuntUncheckedUpdateWithoutStepsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refUser?: Prisma.IntFieldUpdateOperationsInput | number
  participations?: Prisma.ParticipationUncheckedUpdateManyWithoutHuntNestedInput
}

export type HuntCreateWithoutUserInput = {
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  steps?: Prisma.StepCreateNestedManyWithoutHuntInput
  participations?: Prisma.ParticipationCreateNestedManyWithoutHuntInput
}

export type HuntUncheckedCreateWithoutUserInput = {
  id?: number
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  steps?: Prisma.StepUncheckedCreateNestedManyWithoutHuntInput
  participations?: Prisma.ParticipationUncheckedCreateNestedManyWithoutHuntInput
}

export type HuntCreateOrConnectWithoutUserInput = {
  where: Prisma.HuntWhereUniqueInput
  create: Prisma.XOR<Prisma.HuntCreateWithoutUserInput, Prisma.HuntUncheckedCreateWithoutUserInput>
}

export type HuntCreateManyUserInputEnvelope = {
  data: Prisma.HuntCreateManyUserInput | Prisma.HuntCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type HuntUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.HuntWhereUniqueInput
  update: Prisma.XOR<Prisma.HuntUpdateWithoutUserInput, Prisma.HuntUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.HuntCreateWithoutUserInput, Prisma.HuntUncheckedCreateWithoutUserInput>
}

export type HuntUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.HuntWhereUniqueInput
  data: Prisma.XOR<Prisma.HuntUpdateWithoutUserInput, Prisma.HuntUncheckedUpdateWithoutUserInput>
}

export type HuntUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.HuntScalarWhereInput
  data: Prisma.XOR<Prisma.HuntUpdateManyMutationInput, Prisma.HuntUncheckedUpdateManyWithoutUserInput>
}

export type HuntScalarWhereInput = {
  AND?: Prisma.HuntScalarWhereInput | Prisma.HuntScalarWhereInput[]
  OR?: Prisma.HuntScalarWhereInput[]
  NOT?: Prisma.HuntScalarWhereInput | Prisma.HuntScalarWhereInput[]
  id?: Prisma.IntFilter<"Hunt"> | number
  title?: Prisma.StringFilter<"Hunt"> | string
  shortDescription?: Prisma.StringNullableFilter<"Hunt"> | string | null
  description?: Prisma.StringNullableFilter<"Hunt"> | string | null
  startDate?: Prisma.DateTimeNullableFilter<"Hunt"> | Date | string | null
  endDate?: Prisma.DateTimeNullableFilter<"Hunt"> | Date | string | null
  radius?: Prisma.IntFilter<"Hunt"> | number
  coverImage?: Prisma.StringNullableFilter<"Hunt"> | string | null
  status?: Prisma.EnumHuntStatusFilter<"Hunt"> | $Enums.HuntStatus
  rewardType?: Prisma.StringNullableFilter<"Hunt"> | string | null
  rewardValue?: Prisma.StringNullableFilter<"Hunt"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Hunt"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Hunt"> | Date | string
  refUser?: Prisma.IntFilter<"Hunt"> | number
}

export type HuntCreateManyUserInput = {
  id?: number
  title: string
  shortDescription?: string | null
  description?: string | null
  startDate?: Date | string | null
  endDate?: Date | string | null
  radius?: number
  coverImage?: string | null
  status?: $Enums.HuntStatus
  rewardType?: string | null
  rewardValue?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HuntUpdateWithoutUserInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  steps?: Prisma.StepUpdateManyWithoutHuntNestedInput
  participations?: Prisma.ParticipationUpdateManyWithoutHuntNestedInput
}

export type HuntUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  steps?: Prisma.StepUncheckedUpdateManyWithoutHuntNestedInput
  participations?: Prisma.ParticipationUncheckedUpdateManyWithoutHuntNestedInput
}

export type HuntUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  shortDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  radius?: Prisma.IntFieldUpdateOperationsInput | number
  coverImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumHuntStatusFieldUpdateOperationsInput | $Enums.HuntStatus
  rewardType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rewardValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type HuntCountOutputType
 */

export type HuntCountOutputType = {
  steps: number
  participations: number
}

export type HuntCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  steps?: boolean | HuntCountOutputTypeCountStepsArgs
  participations?: boolean | HuntCountOutputTypeCountParticipationsArgs
}

/**
 * HuntCountOutputType without action
 */
export type HuntCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HuntCountOutputType
   */
  select?: Prisma.HuntCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HuntCountOutputType without action
 */
export type HuntCountOutputTypeCountStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StepWhereInput
}

/**
 * HuntCountOutputType without action
 */
export type HuntCountOutputTypeCountParticipationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParticipationWhereInput
}


export type HuntSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  shortDescription?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  radius?: boolean
  coverImage?: boolean
  status?: boolean
  rewardType?: boolean
  rewardValue?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refUser?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  steps?: boolean | Prisma.Hunt$stepsArgs<ExtArgs>
  participations?: boolean | Prisma.Hunt$participationsArgs<ExtArgs>
  _count?: boolean | Prisma.HuntCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hunt"]>

export type HuntSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  shortDescription?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  radius?: boolean
  coverImage?: boolean
  status?: boolean
  rewardType?: boolean
  rewardValue?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refUser?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hunt"]>

export type HuntSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  shortDescription?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  radius?: boolean
  coverImage?: boolean
  status?: boolean
  rewardType?: boolean
  rewardValue?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refUser?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hunt"]>

export type HuntSelectScalar = {
  id?: boolean
  title?: boolean
  shortDescription?: boolean
  description?: boolean
  startDate?: boolean
  endDate?: boolean
  radius?: boolean
  coverImage?: boolean
  status?: boolean
  rewardType?: boolean
  rewardValue?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refUser?: boolean
}

export type HuntOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "shortDescription" | "description" | "startDate" | "endDate" | "radius" | "coverImage" | "status" | "rewardType" | "rewardValue" | "createdAt" | "updatedAt" | "refUser", ExtArgs["result"]["hunt"]>
export type HuntInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  steps?: boolean | Prisma.Hunt$stepsArgs<ExtArgs>
  participations?: boolean | Prisma.Hunt$participationsArgs<ExtArgs>
  _count?: boolean | Prisma.HuntCountOutputTypeDefaultArgs<ExtArgs>
}
export type HuntIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type HuntIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $HuntPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Hunt"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    steps: Prisma.$StepPayload<ExtArgs>[]
    participations: Prisma.$ParticipationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    title: string
    shortDescription: string | null
    description: string | null
    startDate: Date | null
    endDate: Date | null
    radius: number
    coverImage: string | null
    status: $Enums.HuntStatus
    rewardType: string | null
    rewardValue: string | null
    createdAt: Date
    updatedAt: Date
    refUser: number
  }, ExtArgs["result"]["hunt"]>
  composites: {}
}

export type HuntGetPayload<S extends boolean | null | undefined | HuntDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HuntPayload, S>

export type HuntCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HuntFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HuntCountAggregateInputType | true
  }

export interface HuntDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Hunt'], meta: { name: 'Hunt' } }
  /**
   * Find zero or one Hunt that matches the filter.
   * @param {HuntFindUniqueArgs} args - Arguments to find a Hunt
   * @example
   * // Get one Hunt
   * const hunt = await prisma.hunt.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HuntFindUniqueArgs>(args: Prisma.SelectSubset<T, HuntFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hunt that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HuntFindUniqueOrThrowArgs} args - Arguments to find a Hunt
   * @example
   * // Get one Hunt
   * const hunt = await prisma.hunt.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HuntFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HuntFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hunt that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntFindFirstArgs} args - Arguments to find a Hunt
   * @example
   * // Get one Hunt
   * const hunt = await prisma.hunt.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HuntFindFirstArgs>(args?: Prisma.SelectSubset<T, HuntFindFirstArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hunt that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntFindFirstOrThrowArgs} args - Arguments to find a Hunt
   * @example
   * // Get one Hunt
   * const hunt = await prisma.hunt.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HuntFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HuntFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Hunts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Hunts
   * const hunts = await prisma.hunt.findMany()
   * 
   * // Get first 10 Hunts
   * const hunts = await prisma.hunt.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const huntWithIdOnly = await prisma.hunt.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HuntFindManyArgs>(args?: Prisma.SelectSubset<T, HuntFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hunt.
   * @param {HuntCreateArgs} args - Arguments to create a Hunt.
   * @example
   * // Create one Hunt
   * const Hunt = await prisma.hunt.create({
   *   data: {
   *     // ... data to create a Hunt
   *   }
   * })
   * 
   */
  create<T extends HuntCreateArgs>(args: Prisma.SelectSubset<T, HuntCreateArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Hunts.
   * @param {HuntCreateManyArgs} args - Arguments to create many Hunts.
   * @example
   * // Create many Hunts
   * const hunt = await prisma.hunt.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HuntCreateManyArgs>(args?: Prisma.SelectSubset<T, HuntCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Hunts and returns the data saved in the database.
   * @param {HuntCreateManyAndReturnArgs} args - Arguments to create many Hunts.
   * @example
   * // Create many Hunts
   * const hunt = await prisma.hunt.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Hunts and only return the `id`
   * const huntWithIdOnly = await prisma.hunt.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HuntCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HuntCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Hunt.
   * @param {HuntDeleteArgs} args - Arguments to delete one Hunt.
   * @example
   * // Delete one Hunt
   * const Hunt = await prisma.hunt.delete({
   *   where: {
   *     // ... filter to delete one Hunt
   *   }
   * })
   * 
   */
  delete<T extends HuntDeleteArgs>(args: Prisma.SelectSubset<T, HuntDeleteArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hunt.
   * @param {HuntUpdateArgs} args - Arguments to update one Hunt.
   * @example
   * // Update one Hunt
   * const hunt = await prisma.hunt.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HuntUpdateArgs>(args: Prisma.SelectSubset<T, HuntUpdateArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Hunts.
   * @param {HuntDeleteManyArgs} args - Arguments to filter Hunts to delete.
   * @example
   * // Delete a few Hunts
   * const { count } = await prisma.hunt.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HuntDeleteManyArgs>(args?: Prisma.SelectSubset<T, HuntDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hunts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Hunts
   * const hunt = await prisma.hunt.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HuntUpdateManyArgs>(args: Prisma.SelectSubset<T, HuntUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hunts and returns the data updated in the database.
   * @param {HuntUpdateManyAndReturnArgs} args - Arguments to update many Hunts.
   * @example
   * // Update many Hunts
   * const hunt = await prisma.hunt.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Hunts and only return the `id`
   * const huntWithIdOnly = await prisma.hunt.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HuntUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HuntUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Hunt.
   * @param {HuntUpsertArgs} args - Arguments to update or create a Hunt.
   * @example
   * // Update or create a Hunt
   * const hunt = await prisma.hunt.upsert({
   *   create: {
   *     // ... data to create a Hunt
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hunt we want to update
   *   }
   * })
   */
  upsert<T extends HuntUpsertArgs>(args: Prisma.SelectSubset<T, HuntUpsertArgs<ExtArgs>>): Prisma.Prisma__HuntClient<runtime.Types.Result.GetResult<Prisma.$HuntPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Hunts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntCountArgs} args - Arguments to filter Hunts to count.
   * @example
   * // Count the number of Hunts
   * const count = await prisma.hunt.count({
   *   where: {
   *     // ... the filter for the Hunts we want to count
   *   }
   * })
  **/
  count<T extends HuntCountArgs>(
    args?: Prisma.Subset<T, HuntCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HuntCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hunt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HuntAggregateArgs>(args: Prisma.Subset<T, HuntAggregateArgs>): Prisma.PrismaPromise<GetHuntAggregateType<T>>

  /**
   * Group by Hunt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HuntGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HuntGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HuntGroupByArgs['orderBy'] }
      : { orderBy?: HuntGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HuntGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHuntGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Hunt model
 */
readonly fields: HuntFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Hunt.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HuntClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  steps<T extends Prisma.Hunt$stepsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hunt$stepsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  participations<T extends Prisma.Hunt$participationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hunt$participationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Hunt model
 */
export interface HuntFieldRefs {
  readonly id: Prisma.FieldRef<"Hunt", 'Int'>
  readonly title: Prisma.FieldRef<"Hunt", 'String'>
  readonly shortDescription: Prisma.FieldRef<"Hunt", 'String'>
  readonly description: Prisma.FieldRef<"Hunt", 'String'>
  readonly startDate: Prisma.FieldRef<"Hunt", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"Hunt", 'DateTime'>
  readonly radius: Prisma.FieldRef<"Hunt", 'Int'>
  readonly coverImage: Prisma.FieldRef<"Hunt", 'String'>
  readonly status: Prisma.FieldRef<"Hunt", 'HuntStatus'>
  readonly rewardType: Prisma.FieldRef<"Hunt", 'String'>
  readonly rewardValue: Prisma.FieldRef<"Hunt", 'String'>
  readonly createdAt: Prisma.FieldRef<"Hunt", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Hunt", 'DateTime'>
  readonly refUser: Prisma.FieldRef<"Hunt", 'Int'>
}
    

// Custom InputTypes
/**
 * Hunt findUnique
 */
export type HuntFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * Filter, which Hunt to fetch.
   */
  where: Prisma.HuntWhereUniqueInput
}

/**
 * Hunt findUniqueOrThrow
 */
export type HuntFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * Filter, which Hunt to fetch.
   */
  where: Prisma.HuntWhereUniqueInput
}

/**
 * Hunt findFirst
 */
export type HuntFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * Filter, which Hunt to fetch.
   */
  where?: Prisma.HuntWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hunts to fetch.
   */
  orderBy?: Prisma.HuntOrderByWithRelationInput | Prisma.HuntOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Hunts.
   */
  cursor?: Prisma.HuntWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hunts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hunts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hunts.
   */
  distinct?: Prisma.HuntScalarFieldEnum | Prisma.HuntScalarFieldEnum[]
}

/**
 * Hunt findFirstOrThrow
 */
export type HuntFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * Filter, which Hunt to fetch.
   */
  where?: Prisma.HuntWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hunts to fetch.
   */
  orderBy?: Prisma.HuntOrderByWithRelationInput | Prisma.HuntOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Hunts.
   */
  cursor?: Prisma.HuntWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hunts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hunts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hunts.
   */
  distinct?: Prisma.HuntScalarFieldEnum | Prisma.HuntScalarFieldEnum[]
}

/**
 * Hunt findMany
 */
export type HuntFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * Filter, which Hunts to fetch.
   */
  where?: Prisma.HuntWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hunts to fetch.
   */
  orderBy?: Prisma.HuntOrderByWithRelationInput | Prisma.HuntOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Hunts.
   */
  cursor?: Prisma.HuntWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hunts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hunts.
   */
  skip?: number
  distinct?: Prisma.HuntScalarFieldEnum | Prisma.HuntScalarFieldEnum[]
}

/**
 * Hunt create
 */
export type HuntCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * The data needed to create a Hunt.
   */
  data: Prisma.XOR<Prisma.HuntCreateInput, Prisma.HuntUncheckedCreateInput>
}

/**
 * Hunt createMany
 */
export type HuntCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Hunts.
   */
  data: Prisma.HuntCreateManyInput | Prisma.HuntCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Hunt createManyAndReturn
 */
export type HuntCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * The data used to create many Hunts.
   */
  data: Prisma.HuntCreateManyInput | Prisma.HuntCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Hunt update
 */
export type HuntUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * The data needed to update a Hunt.
   */
  data: Prisma.XOR<Prisma.HuntUpdateInput, Prisma.HuntUncheckedUpdateInput>
  /**
   * Choose, which Hunt to update.
   */
  where: Prisma.HuntWhereUniqueInput
}

/**
 * Hunt updateMany
 */
export type HuntUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Hunts.
   */
  data: Prisma.XOR<Prisma.HuntUpdateManyMutationInput, Prisma.HuntUncheckedUpdateManyInput>
  /**
   * Filter which Hunts to update
   */
  where?: Prisma.HuntWhereInput
  /**
   * Limit how many Hunts to update.
   */
  limit?: number
}

/**
 * Hunt updateManyAndReturn
 */
export type HuntUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * The data used to update Hunts.
   */
  data: Prisma.XOR<Prisma.HuntUpdateManyMutationInput, Prisma.HuntUncheckedUpdateManyInput>
  /**
   * Filter which Hunts to update
   */
  where?: Prisma.HuntWhereInput
  /**
   * Limit how many Hunts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Hunt upsert
 */
export type HuntUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * The filter to search for the Hunt to update in case it exists.
   */
  where: Prisma.HuntWhereUniqueInput
  /**
   * In case the Hunt found by the `where` argument doesn't exist, create a new Hunt with this data.
   */
  create: Prisma.XOR<Prisma.HuntCreateInput, Prisma.HuntUncheckedCreateInput>
  /**
   * In case the Hunt was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HuntUpdateInput, Prisma.HuntUncheckedUpdateInput>
}

/**
 * Hunt delete
 */
export type HuntDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
  /**
   * Filter which Hunt to delete.
   */
  where: Prisma.HuntWhereUniqueInput
}

/**
 * Hunt deleteMany
 */
export type HuntDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hunts to delete
   */
  where?: Prisma.HuntWhereInput
  /**
   * Limit how many Hunts to delete.
   */
  limit?: number
}

/**
 * Hunt.steps
 */
export type Hunt$stepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Step
   */
  select?: Prisma.StepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Step
   */
  omit?: Prisma.StepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StepInclude<ExtArgs> | null
  where?: Prisma.StepWhereInput
  orderBy?: Prisma.StepOrderByWithRelationInput | Prisma.StepOrderByWithRelationInput[]
  cursor?: Prisma.StepWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StepScalarFieldEnum | Prisma.StepScalarFieldEnum[]
}

/**
 * Hunt.participations
 */
export type Hunt$participationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  where?: Prisma.ParticipationWhereInput
  orderBy?: Prisma.ParticipationOrderByWithRelationInput | Prisma.ParticipationOrderByWithRelationInput[]
  cursor?: Prisma.ParticipationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ParticipationScalarFieldEnum | Prisma.ParticipationScalarFieldEnum[]
}

/**
 * Hunt without action
 */
export type HuntDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hunt
   */
  select?: Prisma.HuntSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hunt
   */
  omit?: Prisma.HuntOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HuntInclude<ExtArgs> | null
}
