
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Progress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Progress
 * 
 */
export type ProgressModel = runtime.Types.Result.DefaultSelection<Prisma.$ProgressPayload>

export type AggregateProgress = {
  _count: ProgressCountAggregateOutputType | null
  _avg: ProgressAvgAggregateOutputType | null
  _sum: ProgressSumAggregateOutputType | null
  _min: ProgressMinAggregateOutputType | null
  _max: ProgressMaxAggregateOutputType | null
}

export type ProgressAvgAggregateOutputType = {
  id: number | null
  totalPoints: number | null
  refParticipation: number | null
  refStep: number | null
}

export type ProgressSumAggregateOutputType = {
  id: number | null
  totalPoints: number | null
  refParticipation: number | null
  refStep: number | null
}

export type ProgressMinAggregateOutputType = {
  id: number | null
  statut: $Enums.ProgressStatus | null
  totalPoints: number | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  refParticipation: number | null
  refStep: number | null
}

export type ProgressMaxAggregateOutputType = {
  id: number | null
  statut: $Enums.ProgressStatus | null
  totalPoints: number | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  refParticipation: number | null
  refStep: number | null
}

export type ProgressCountAggregateOutputType = {
  id: number
  statut: number
  totalPoints: number
  startedAt: number
  completedAt: number
  createdAt: number
  updatedAt: number
  refParticipation: number
  refStep: number
  _all: number
}


export type ProgressAvgAggregateInputType = {
  id?: true
  totalPoints?: true
  refParticipation?: true
  refStep?: true
}

export type ProgressSumAggregateInputType = {
  id?: true
  totalPoints?: true
  refParticipation?: true
  refStep?: true
}

export type ProgressMinAggregateInputType = {
  id?: true
  statut?: true
  totalPoints?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  refParticipation?: true
  refStep?: true
}

export type ProgressMaxAggregateInputType = {
  id?: true
  statut?: true
  totalPoints?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  refParticipation?: true
  refStep?: true
}

export type ProgressCountAggregateInputType = {
  id?: true
  statut?: true
  totalPoints?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  updatedAt?: true
  refParticipation?: true
  refStep?: true
  _all?: true
}

export type ProgressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Progress to aggregate.
   */
  where?: Prisma.ProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Progresses to fetch.
   */
  orderBy?: Prisma.ProgressOrderByWithRelationInput | Prisma.ProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Progresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Progresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Progresses
  **/
  _count?: true | ProgressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProgressAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProgressSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProgressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProgressMaxAggregateInputType
}

export type GetProgressAggregateType<T extends ProgressAggregateArgs> = {
      [P in keyof T & keyof AggregateProgress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProgress[P]>
    : Prisma.GetScalarType<T[P], AggregateProgress[P]>
}




export type ProgressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProgressWhereInput
  orderBy?: Prisma.ProgressOrderByWithAggregationInput | Prisma.ProgressOrderByWithAggregationInput[]
  by: Prisma.ProgressScalarFieldEnum[] | Prisma.ProgressScalarFieldEnum
  having?: Prisma.ProgressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProgressCountAggregateInputType | true
  _avg?: ProgressAvgAggregateInputType
  _sum?: ProgressSumAggregateInputType
  _min?: ProgressMinAggregateInputType
  _max?: ProgressMaxAggregateInputType
}

export type ProgressGroupByOutputType = {
  id: number
  statut: $Enums.ProgressStatus
  totalPoints: number
  startedAt: Date
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date
  refParticipation: number
  refStep: number
  _count: ProgressCountAggregateOutputType | null
  _avg: ProgressAvgAggregateOutputType | null
  _sum: ProgressSumAggregateOutputType | null
  _min: ProgressMinAggregateOutputType | null
  _max: ProgressMaxAggregateOutputType | null
}

type GetProgressGroupByPayload<T extends ProgressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProgressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProgressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProgressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProgressGroupByOutputType[P]>
      }
    >
  >



export type ProgressWhereInput = {
  AND?: Prisma.ProgressWhereInput | Prisma.ProgressWhereInput[]
  OR?: Prisma.ProgressWhereInput[]
  NOT?: Prisma.ProgressWhereInput | Prisma.ProgressWhereInput[]
  id?: Prisma.IntFilter<"Progress"> | number
  statut?: Prisma.EnumProgressStatusFilter<"Progress"> | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFilter<"Progress"> | number
  startedAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Progress"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  refParticipation?: Prisma.IntFilter<"Progress"> | number
  refStep?: Prisma.IntFilter<"Progress"> | number
  participation?: Prisma.XOR<Prisma.ParticipationScalarRelationFilter, Prisma.ParticipationWhereInput>
  step?: Prisma.XOR<Prisma.StepScalarRelationFilter, Prisma.StepWhereInput>
  clueUsages?: Prisma.ClueUsageListRelationFilter
}

export type ProgressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
  participation?: Prisma.ParticipationOrderByWithRelationInput
  step?: Prisma.StepOrderByWithRelationInput
  clueUsages?: Prisma.ClueUsageOrderByRelationAggregateInput
}

export type ProgressWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  refParticipation_refStep?: Prisma.ProgressRefParticipationRefStepCompoundUniqueInput
  AND?: Prisma.ProgressWhereInput | Prisma.ProgressWhereInput[]
  OR?: Prisma.ProgressWhereInput[]
  NOT?: Prisma.ProgressWhereInput | Prisma.ProgressWhereInput[]
  statut?: Prisma.EnumProgressStatusFilter<"Progress"> | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFilter<"Progress"> | number
  startedAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Progress"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  refParticipation?: Prisma.IntFilter<"Progress"> | number
  refStep?: Prisma.IntFilter<"Progress"> | number
  participation?: Prisma.XOR<Prisma.ParticipationScalarRelationFilter, Prisma.ParticipationWhereInput>
  step?: Prisma.XOR<Prisma.StepScalarRelationFilter, Prisma.StepWhereInput>
  clueUsages?: Prisma.ClueUsageListRelationFilter
}, "id" | "refParticipation_refStep">

export type ProgressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
  _count?: Prisma.ProgressCountOrderByAggregateInput
  _avg?: Prisma.ProgressAvgOrderByAggregateInput
  _max?: Prisma.ProgressMaxOrderByAggregateInput
  _min?: Prisma.ProgressMinOrderByAggregateInput
  _sum?: Prisma.ProgressSumOrderByAggregateInput
}

export type ProgressScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProgressScalarWhereWithAggregatesInput | Prisma.ProgressScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProgressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProgressScalarWhereWithAggregatesInput | Prisma.ProgressScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Progress"> | number
  statut?: Prisma.EnumProgressStatusWithAggregatesFilter<"Progress"> | $Enums.ProgressStatus
  totalPoints?: Prisma.IntWithAggregatesFilter<"Progress"> | number
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"Progress"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Progress"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Progress"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Progress"> | Date | string
  refParticipation?: Prisma.IntWithAggregatesFilter<"Progress"> | number
  refStep?: Prisma.IntWithAggregatesFilter<"Progress"> | number
}

export type ProgressCreateInput = {
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  participation: Prisma.ParticipationCreateNestedOneWithoutProgressesInput
  step: Prisma.StepCreateNestedOneWithoutProgressesInput
  clueUsages?: Prisma.ClueUsageCreateNestedManyWithoutProgressInput
}

export type ProgressUncheckedCreateInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refParticipation: number
  refStep: number
  clueUsages?: Prisma.ClueUsageUncheckedCreateNestedManyWithoutProgressInput
}

export type ProgressUpdateInput = {
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participation?: Prisma.ParticipationUpdateOneRequiredWithoutProgressesNestedInput
  step?: Prisma.StepUpdateOneRequiredWithoutProgressesNestedInput
  clueUsages?: Prisma.ClueUsageUpdateManyWithoutProgressNestedInput
}

export type ProgressUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refParticipation?: Prisma.IntFieldUpdateOperationsInput | number
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
  clueUsages?: Prisma.ClueUsageUncheckedUpdateManyWithoutProgressNestedInput
}

export type ProgressCreateManyInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refParticipation: number
  refStep: number
}

export type ProgressUpdateManyMutationInput = {
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProgressUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refParticipation?: Prisma.IntFieldUpdateOperationsInput | number
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ProgressScalarRelationFilter = {
  is?: Prisma.ProgressWhereInput
  isNot?: Prisma.ProgressWhereInput
}

export type ProgressListRelationFilter = {
  every?: Prisma.ProgressWhereInput
  some?: Prisma.ProgressWhereInput
  none?: Prisma.ProgressWhereInput
}

export type ProgressOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProgressRefParticipationRefStepCompoundUniqueInput = {
  refParticipation: number
  refStep: number
}

export type ProgressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ProgressAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ProgressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ProgressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  statut?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ProgressSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  totalPoints?: Prisma.SortOrder
  refParticipation?: Prisma.SortOrder
  refStep?: Prisma.SortOrder
}

export type ProgressCreateNestedOneWithoutClueUsagesInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutClueUsagesInput, Prisma.ProgressUncheckedCreateWithoutClueUsagesInput>
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutClueUsagesInput
  connect?: Prisma.ProgressWhereUniqueInput
}

export type ProgressUpdateOneRequiredWithoutClueUsagesNestedInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutClueUsagesInput, Prisma.ProgressUncheckedCreateWithoutClueUsagesInput>
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutClueUsagesInput
  upsert?: Prisma.ProgressUpsertWithoutClueUsagesInput
  connect?: Prisma.ProgressWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProgressUpdateToOneWithWhereWithoutClueUsagesInput, Prisma.ProgressUpdateWithoutClueUsagesInput>, Prisma.ProgressUncheckedUpdateWithoutClueUsagesInput>
}

export type ProgressCreateNestedManyWithoutParticipationInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutParticipationInput, Prisma.ProgressUncheckedCreateWithoutParticipationInput> | Prisma.ProgressCreateWithoutParticipationInput[] | Prisma.ProgressUncheckedCreateWithoutParticipationInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutParticipationInput | Prisma.ProgressCreateOrConnectWithoutParticipationInput[]
  createMany?: Prisma.ProgressCreateManyParticipationInputEnvelope
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
}

export type ProgressUncheckedCreateNestedManyWithoutParticipationInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutParticipationInput, Prisma.ProgressUncheckedCreateWithoutParticipationInput> | Prisma.ProgressCreateWithoutParticipationInput[] | Prisma.ProgressUncheckedCreateWithoutParticipationInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutParticipationInput | Prisma.ProgressCreateOrConnectWithoutParticipationInput[]
  createMany?: Prisma.ProgressCreateManyParticipationInputEnvelope
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
}

export type ProgressUpdateManyWithoutParticipationNestedInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutParticipationInput, Prisma.ProgressUncheckedCreateWithoutParticipationInput> | Prisma.ProgressCreateWithoutParticipationInput[] | Prisma.ProgressUncheckedCreateWithoutParticipationInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutParticipationInput | Prisma.ProgressCreateOrConnectWithoutParticipationInput[]
  upsert?: Prisma.ProgressUpsertWithWhereUniqueWithoutParticipationInput | Prisma.ProgressUpsertWithWhereUniqueWithoutParticipationInput[]
  createMany?: Prisma.ProgressCreateManyParticipationInputEnvelope
  set?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  disconnect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  delete?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  update?: Prisma.ProgressUpdateWithWhereUniqueWithoutParticipationInput | Prisma.ProgressUpdateWithWhereUniqueWithoutParticipationInput[]
  updateMany?: Prisma.ProgressUpdateManyWithWhereWithoutParticipationInput | Prisma.ProgressUpdateManyWithWhereWithoutParticipationInput[]
  deleteMany?: Prisma.ProgressScalarWhereInput | Prisma.ProgressScalarWhereInput[]
}

export type ProgressUncheckedUpdateManyWithoutParticipationNestedInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutParticipationInput, Prisma.ProgressUncheckedCreateWithoutParticipationInput> | Prisma.ProgressCreateWithoutParticipationInput[] | Prisma.ProgressUncheckedCreateWithoutParticipationInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutParticipationInput | Prisma.ProgressCreateOrConnectWithoutParticipationInput[]
  upsert?: Prisma.ProgressUpsertWithWhereUniqueWithoutParticipationInput | Prisma.ProgressUpsertWithWhereUniqueWithoutParticipationInput[]
  createMany?: Prisma.ProgressCreateManyParticipationInputEnvelope
  set?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  disconnect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  delete?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  update?: Prisma.ProgressUpdateWithWhereUniqueWithoutParticipationInput | Prisma.ProgressUpdateWithWhereUniqueWithoutParticipationInput[]
  updateMany?: Prisma.ProgressUpdateManyWithWhereWithoutParticipationInput | Prisma.ProgressUpdateManyWithWhereWithoutParticipationInput[]
  deleteMany?: Prisma.ProgressScalarWhereInput | Prisma.ProgressScalarWhereInput[]
}

export type EnumProgressStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProgressStatus
}

export type ProgressCreateNestedManyWithoutStepInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutStepInput, Prisma.ProgressUncheckedCreateWithoutStepInput> | Prisma.ProgressCreateWithoutStepInput[] | Prisma.ProgressUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutStepInput | Prisma.ProgressCreateOrConnectWithoutStepInput[]
  createMany?: Prisma.ProgressCreateManyStepInputEnvelope
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
}

export type ProgressUncheckedCreateNestedManyWithoutStepInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutStepInput, Prisma.ProgressUncheckedCreateWithoutStepInput> | Prisma.ProgressCreateWithoutStepInput[] | Prisma.ProgressUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutStepInput | Prisma.ProgressCreateOrConnectWithoutStepInput[]
  createMany?: Prisma.ProgressCreateManyStepInputEnvelope
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
}

export type ProgressUpdateManyWithoutStepNestedInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutStepInput, Prisma.ProgressUncheckedCreateWithoutStepInput> | Prisma.ProgressCreateWithoutStepInput[] | Prisma.ProgressUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutStepInput | Prisma.ProgressCreateOrConnectWithoutStepInput[]
  upsert?: Prisma.ProgressUpsertWithWhereUniqueWithoutStepInput | Prisma.ProgressUpsertWithWhereUniqueWithoutStepInput[]
  createMany?: Prisma.ProgressCreateManyStepInputEnvelope
  set?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  disconnect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  delete?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  update?: Prisma.ProgressUpdateWithWhereUniqueWithoutStepInput | Prisma.ProgressUpdateWithWhereUniqueWithoutStepInput[]
  updateMany?: Prisma.ProgressUpdateManyWithWhereWithoutStepInput | Prisma.ProgressUpdateManyWithWhereWithoutStepInput[]
  deleteMany?: Prisma.ProgressScalarWhereInput | Prisma.ProgressScalarWhereInput[]
}

export type ProgressUncheckedUpdateManyWithoutStepNestedInput = {
  create?: Prisma.XOR<Prisma.ProgressCreateWithoutStepInput, Prisma.ProgressUncheckedCreateWithoutStepInput> | Prisma.ProgressCreateWithoutStepInput[] | Prisma.ProgressUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.ProgressCreateOrConnectWithoutStepInput | Prisma.ProgressCreateOrConnectWithoutStepInput[]
  upsert?: Prisma.ProgressUpsertWithWhereUniqueWithoutStepInput | Prisma.ProgressUpsertWithWhereUniqueWithoutStepInput[]
  createMany?: Prisma.ProgressCreateManyStepInputEnvelope
  set?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  disconnect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  delete?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  connect?: Prisma.ProgressWhereUniqueInput | Prisma.ProgressWhereUniqueInput[]
  update?: Prisma.ProgressUpdateWithWhereUniqueWithoutStepInput | Prisma.ProgressUpdateWithWhereUniqueWithoutStepInput[]
  updateMany?: Prisma.ProgressUpdateManyWithWhereWithoutStepInput | Prisma.ProgressUpdateManyWithWhereWithoutStepInput[]
  deleteMany?: Prisma.ProgressScalarWhereInput | Prisma.ProgressScalarWhereInput[]
}

export type ProgressCreateWithoutClueUsagesInput = {
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  participation: Prisma.ParticipationCreateNestedOneWithoutProgressesInput
  step: Prisma.StepCreateNestedOneWithoutProgressesInput
}

export type ProgressUncheckedCreateWithoutClueUsagesInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refParticipation: number
  refStep: number
}

export type ProgressCreateOrConnectWithoutClueUsagesInput = {
  where: Prisma.ProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgressCreateWithoutClueUsagesInput, Prisma.ProgressUncheckedCreateWithoutClueUsagesInput>
}

export type ProgressUpsertWithoutClueUsagesInput = {
  update: Prisma.XOR<Prisma.ProgressUpdateWithoutClueUsagesInput, Prisma.ProgressUncheckedUpdateWithoutClueUsagesInput>
  create: Prisma.XOR<Prisma.ProgressCreateWithoutClueUsagesInput, Prisma.ProgressUncheckedCreateWithoutClueUsagesInput>
  where?: Prisma.ProgressWhereInput
}

export type ProgressUpdateToOneWithWhereWithoutClueUsagesInput = {
  where?: Prisma.ProgressWhereInput
  data: Prisma.XOR<Prisma.ProgressUpdateWithoutClueUsagesInput, Prisma.ProgressUncheckedUpdateWithoutClueUsagesInput>
}

export type ProgressUpdateWithoutClueUsagesInput = {
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participation?: Prisma.ParticipationUpdateOneRequiredWithoutProgressesNestedInput
  step?: Prisma.StepUpdateOneRequiredWithoutProgressesNestedInput
}

export type ProgressUncheckedUpdateWithoutClueUsagesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refParticipation?: Prisma.IntFieldUpdateOperationsInput | number
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ProgressCreateWithoutParticipationInput = {
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  step: Prisma.StepCreateNestedOneWithoutProgressesInput
  clueUsages?: Prisma.ClueUsageCreateNestedManyWithoutProgressInput
}

export type ProgressUncheckedCreateWithoutParticipationInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refStep: number
  clueUsages?: Prisma.ClueUsageUncheckedCreateNestedManyWithoutProgressInput
}

export type ProgressCreateOrConnectWithoutParticipationInput = {
  where: Prisma.ProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgressCreateWithoutParticipationInput, Prisma.ProgressUncheckedCreateWithoutParticipationInput>
}

export type ProgressCreateManyParticipationInputEnvelope = {
  data: Prisma.ProgressCreateManyParticipationInput | Prisma.ProgressCreateManyParticipationInput[]
  skipDuplicates?: boolean
}

export type ProgressUpsertWithWhereUniqueWithoutParticipationInput = {
  where: Prisma.ProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.ProgressUpdateWithoutParticipationInput, Prisma.ProgressUncheckedUpdateWithoutParticipationInput>
  create: Prisma.XOR<Prisma.ProgressCreateWithoutParticipationInput, Prisma.ProgressUncheckedCreateWithoutParticipationInput>
}

export type ProgressUpdateWithWhereUniqueWithoutParticipationInput = {
  where: Prisma.ProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.ProgressUpdateWithoutParticipationInput, Prisma.ProgressUncheckedUpdateWithoutParticipationInput>
}

export type ProgressUpdateManyWithWhereWithoutParticipationInput = {
  where: Prisma.ProgressScalarWhereInput
  data: Prisma.XOR<Prisma.ProgressUpdateManyMutationInput, Prisma.ProgressUncheckedUpdateManyWithoutParticipationInput>
}

export type ProgressScalarWhereInput = {
  AND?: Prisma.ProgressScalarWhereInput | Prisma.ProgressScalarWhereInput[]
  OR?: Prisma.ProgressScalarWhereInput[]
  NOT?: Prisma.ProgressScalarWhereInput | Prisma.ProgressScalarWhereInput[]
  id?: Prisma.IntFilter<"Progress"> | number
  statut?: Prisma.EnumProgressStatusFilter<"Progress"> | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFilter<"Progress"> | number
  startedAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Progress"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Progress"> | Date | string
  refParticipation?: Prisma.IntFilter<"Progress"> | number
  refStep?: Prisma.IntFilter<"Progress"> | number
}

export type ProgressCreateWithoutStepInput = {
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  participation: Prisma.ParticipationCreateNestedOneWithoutProgressesInput
  clueUsages?: Prisma.ClueUsageCreateNestedManyWithoutProgressInput
}

export type ProgressUncheckedCreateWithoutStepInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refParticipation: number
  clueUsages?: Prisma.ClueUsageUncheckedCreateNestedManyWithoutProgressInput
}

export type ProgressCreateOrConnectWithoutStepInput = {
  where: Prisma.ProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.ProgressCreateWithoutStepInput, Prisma.ProgressUncheckedCreateWithoutStepInput>
}

export type ProgressCreateManyStepInputEnvelope = {
  data: Prisma.ProgressCreateManyStepInput | Prisma.ProgressCreateManyStepInput[]
  skipDuplicates?: boolean
}

export type ProgressUpsertWithWhereUniqueWithoutStepInput = {
  where: Prisma.ProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.ProgressUpdateWithoutStepInput, Prisma.ProgressUncheckedUpdateWithoutStepInput>
  create: Prisma.XOR<Prisma.ProgressCreateWithoutStepInput, Prisma.ProgressUncheckedCreateWithoutStepInput>
}

export type ProgressUpdateWithWhereUniqueWithoutStepInput = {
  where: Prisma.ProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.ProgressUpdateWithoutStepInput, Prisma.ProgressUncheckedUpdateWithoutStepInput>
}

export type ProgressUpdateManyWithWhereWithoutStepInput = {
  where: Prisma.ProgressScalarWhereInput
  data: Prisma.XOR<Prisma.ProgressUpdateManyMutationInput, Prisma.ProgressUncheckedUpdateManyWithoutStepInput>
}

export type ProgressCreateManyParticipationInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refStep: number
}

export type ProgressUpdateWithoutParticipationInput = {
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  step?: Prisma.StepUpdateOneRequiredWithoutProgressesNestedInput
  clueUsages?: Prisma.ClueUsageUpdateManyWithoutProgressNestedInput
}

export type ProgressUncheckedUpdateWithoutParticipationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
  clueUsages?: Prisma.ClueUsageUncheckedUpdateManyWithoutProgressNestedInput
}

export type ProgressUncheckedUpdateManyWithoutParticipationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refStep?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ProgressCreateManyStepInput = {
  id?: number
  statut?: $Enums.ProgressStatus
  totalPoints?: number
  startedAt?: Date | string
  completedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  refParticipation: number
}

export type ProgressUpdateWithoutStepInput = {
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participation?: Prisma.ParticipationUpdateOneRequiredWithoutProgressesNestedInput
  clueUsages?: Prisma.ClueUsageUpdateManyWithoutProgressNestedInput
}

export type ProgressUncheckedUpdateWithoutStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refParticipation?: Prisma.IntFieldUpdateOperationsInput | number
  clueUsages?: Prisma.ClueUsageUncheckedUpdateManyWithoutProgressNestedInput
}

export type ProgressUncheckedUpdateManyWithoutStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  statut?: Prisma.EnumProgressStatusFieldUpdateOperationsInput | $Enums.ProgressStatus
  totalPoints?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  refParticipation?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ProgressCountOutputType
 */

export type ProgressCountOutputType = {
  clueUsages: number
}

export type ProgressCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  clueUsages?: boolean | ProgressCountOutputTypeCountClueUsagesArgs
}

/**
 * ProgressCountOutputType without action
 */
export type ProgressCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProgressCountOutputType
   */
  select?: Prisma.ProgressCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProgressCountOutputType without action
 */
export type ProgressCountOutputTypeCountClueUsagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClueUsageWhereInput
}


export type ProgressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  statut?: boolean
  totalPoints?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refParticipation?: boolean
  refStep?: boolean
  participation?: boolean | Prisma.ParticipationDefaultArgs<ExtArgs>
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
  clueUsages?: boolean | Prisma.Progress$clueUsagesArgs<ExtArgs>
  _count?: boolean | Prisma.ProgressCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["progress"]>

export type ProgressSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  statut?: boolean
  totalPoints?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refParticipation?: boolean
  refStep?: boolean
  participation?: boolean | Prisma.ParticipationDefaultArgs<ExtArgs>
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["progress"]>

export type ProgressSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  statut?: boolean
  totalPoints?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refParticipation?: boolean
  refStep?: boolean
  participation?: boolean | Prisma.ParticipationDefaultArgs<ExtArgs>
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["progress"]>

export type ProgressSelectScalar = {
  id?: boolean
  statut?: boolean
  totalPoints?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  refParticipation?: boolean
  refStep?: boolean
}

export type ProgressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "statut" | "totalPoints" | "startedAt" | "completedAt" | "createdAt" | "updatedAt" | "refParticipation" | "refStep", ExtArgs["result"]["progress"]>
export type ProgressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participation?: boolean | Prisma.ParticipationDefaultArgs<ExtArgs>
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
  clueUsages?: boolean | Prisma.Progress$clueUsagesArgs<ExtArgs>
  _count?: boolean | Prisma.ProgressCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProgressIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participation?: boolean | Prisma.ParticipationDefaultArgs<ExtArgs>
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}
export type ProgressIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participation?: boolean | Prisma.ParticipationDefaultArgs<ExtArgs>
  step?: boolean | Prisma.StepDefaultArgs<ExtArgs>
}

export type $ProgressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Progress"
  objects: {
    participation: Prisma.$ParticipationPayload<ExtArgs>
    step: Prisma.$StepPayload<ExtArgs>
    clueUsages: Prisma.$ClueUsagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    statut: $Enums.ProgressStatus
    totalPoints: number
    startedAt: Date
    completedAt: Date | null
    createdAt: Date
    updatedAt: Date
    refParticipation: number
    refStep: number
  }, ExtArgs["result"]["progress"]>
  composites: {}
}

export type ProgressGetPayload<S extends boolean | null | undefined | ProgressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProgressPayload, S>

export type ProgressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProgressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProgressCountAggregateInputType | true
  }

export interface ProgressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Progress'], meta: { name: 'Progress' } }
  /**
   * Find zero or one Progress that matches the filter.
   * @param {ProgressFindUniqueArgs} args - Arguments to find a Progress
   * @example
   * // Get one Progress
   * const progress = await prisma.progress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProgressFindUniqueArgs>(args: Prisma.SelectSubset<T, ProgressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Progress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProgressFindUniqueOrThrowArgs} args - Arguments to find a Progress
   * @example
   * // Get one Progress
   * const progress = await prisma.progress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProgressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProgressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Progress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressFindFirstArgs} args - Arguments to find a Progress
   * @example
   * // Get one Progress
   * const progress = await prisma.progress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProgressFindFirstArgs>(args?: Prisma.SelectSubset<T, ProgressFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Progress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressFindFirstOrThrowArgs} args - Arguments to find a Progress
   * @example
   * // Get one Progress
   * const progress = await prisma.progress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProgressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProgressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Progresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Progresses
   * const progresses = await prisma.progress.findMany()
   * 
   * // Get first 10 Progresses
   * const progresses = await prisma.progress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const progressWithIdOnly = await prisma.progress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProgressFindManyArgs>(args?: Prisma.SelectSubset<T, ProgressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Progress.
   * @param {ProgressCreateArgs} args - Arguments to create a Progress.
   * @example
   * // Create one Progress
   * const Progress = await prisma.progress.create({
   *   data: {
   *     // ... data to create a Progress
   *   }
   * })
   * 
   */
  create<T extends ProgressCreateArgs>(args: Prisma.SelectSubset<T, ProgressCreateArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Progresses.
   * @param {ProgressCreateManyArgs} args - Arguments to create many Progresses.
   * @example
   * // Create many Progresses
   * const progress = await prisma.progress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProgressCreateManyArgs>(args?: Prisma.SelectSubset<T, ProgressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Progresses and returns the data saved in the database.
   * @param {ProgressCreateManyAndReturnArgs} args - Arguments to create many Progresses.
   * @example
   * // Create many Progresses
   * const progress = await prisma.progress.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Progresses and only return the `id`
   * const progressWithIdOnly = await prisma.progress.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProgressCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProgressCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Progress.
   * @param {ProgressDeleteArgs} args - Arguments to delete one Progress.
   * @example
   * // Delete one Progress
   * const Progress = await prisma.progress.delete({
   *   where: {
   *     // ... filter to delete one Progress
   *   }
   * })
   * 
   */
  delete<T extends ProgressDeleteArgs>(args: Prisma.SelectSubset<T, ProgressDeleteArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Progress.
   * @param {ProgressUpdateArgs} args - Arguments to update one Progress.
   * @example
   * // Update one Progress
   * const progress = await prisma.progress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProgressUpdateArgs>(args: Prisma.SelectSubset<T, ProgressUpdateArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Progresses.
   * @param {ProgressDeleteManyArgs} args - Arguments to filter Progresses to delete.
   * @example
   * // Delete a few Progresses
   * const { count } = await prisma.progress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProgressDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProgressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Progresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Progresses
   * const progress = await prisma.progress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProgressUpdateManyArgs>(args: Prisma.SelectSubset<T, ProgressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Progresses and returns the data updated in the database.
   * @param {ProgressUpdateManyAndReturnArgs} args - Arguments to update many Progresses.
   * @example
   * // Update many Progresses
   * const progress = await prisma.progress.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Progresses and only return the `id`
   * const progressWithIdOnly = await prisma.progress.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProgressUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProgressUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Progress.
   * @param {ProgressUpsertArgs} args - Arguments to update or create a Progress.
   * @example
   * // Update or create a Progress
   * const progress = await prisma.progress.upsert({
   *   create: {
   *     // ... data to create a Progress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Progress we want to update
   *   }
   * })
   */
  upsert<T extends ProgressUpsertArgs>(args: Prisma.SelectSubset<T, ProgressUpsertArgs<ExtArgs>>): Prisma.Prisma__ProgressClient<runtime.Types.Result.GetResult<Prisma.$ProgressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Progresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressCountArgs} args - Arguments to filter Progresses to count.
   * @example
   * // Count the number of Progresses
   * const count = await prisma.progress.count({
   *   where: {
   *     // ... the filter for the Progresses we want to count
   *   }
   * })
  **/
  count<T extends ProgressCountArgs>(
    args?: Prisma.Subset<T, ProgressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProgressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Progress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProgressAggregateArgs>(args: Prisma.Subset<T, ProgressAggregateArgs>): Prisma.PrismaPromise<GetProgressAggregateType<T>>

  /**
   * Group by Progress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProgressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProgressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProgressGroupByArgs['orderBy'] }
      : { orderBy?: ProgressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProgressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProgressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Progress model
 */
readonly fields: ProgressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Progress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProgressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participation<T extends Prisma.ParticipationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ParticipationDefaultArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  step<T extends Prisma.StepDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StepDefaultArgs<ExtArgs>>): Prisma.Prisma__StepClient<runtime.Types.Result.GetResult<Prisma.$StepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  clueUsages<T extends Prisma.Progress$clueUsagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Progress$clueUsagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClueUsagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Progress model
 */
export interface ProgressFieldRefs {
  readonly id: Prisma.FieldRef<"Progress", 'Int'>
  readonly statut: Prisma.FieldRef<"Progress", 'ProgressStatus'>
  readonly totalPoints: Prisma.FieldRef<"Progress", 'Int'>
  readonly startedAt: Prisma.FieldRef<"Progress", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"Progress", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Progress", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Progress", 'DateTime'>
  readonly refParticipation: Prisma.FieldRef<"Progress", 'Int'>
  readonly refStep: Prisma.FieldRef<"Progress", 'Int'>
}
    

// Custom InputTypes
/**
 * Progress findUnique
 */
export type ProgressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * Filter, which Progress to fetch.
   */
  where: Prisma.ProgressWhereUniqueInput
}

/**
 * Progress findUniqueOrThrow
 */
export type ProgressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * Filter, which Progress to fetch.
   */
  where: Prisma.ProgressWhereUniqueInput
}

/**
 * Progress findFirst
 */
export type ProgressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * Filter, which Progress to fetch.
   */
  where?: Prisma.ProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Progresses to fetch.
   */
  orderBy?: Prisma.ProgressOrderByWithRelationInput | Prisma.ProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Progresses.
   */
  cursor?: Prisma.ProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Progresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Progresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Progresses.
   */
  distinct?: Prisma.ProgressScalarFieldEnum | Prisma.ProgressScalarFieldEnum[]
}

/**
 * Progress findFirstOrThrow
 */
export type ProgressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * Filter, which Progress to fetch.
   */
  where?: Prisma.ProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Progresses to fetch.
   */
  orderBy?: Prisma.ProgressOrderByWithRelationInput | Prisma.ProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Progresses.
   */
  cursor?: Prisma.ProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Progresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Progresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Progresses.
   */
  distinct?: Prisma.ProgressScalarFieldEnum | Prisma.ProgressScalarFieldEnum[]
}

/**
 * Progress findMany
 */
export type ProgressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * Filter, which Progresses to fetch.
   */
  where?: Prisma.ProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Progresses to fetch.
   */
  orderBy?: Prisma.ProgressOrderByWithRelationInput | Prisma.ProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Progresses.
   */
  cursor?: Prisma.ProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Progresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Progresses.
   */
  skip?: number
  distinct?: Prisma.ProgressScalarFieldEnum | Prisma.ProgressScalarFieldEnum[]
}

/**
 * Progress create
 */
export type ProgressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * The data needed to create a Progress.
   */
  data: Prisma.XOR<Prisma.ProgressCreateInput, Prisma.ProgressUncheckedCreateInput>
}

/**
 * Progress createMany
 */
export type ProgressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Progresses.
   */
  data: Prisma.ProgressCreateManyInput | Prisma.ProgressCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Progress createManyAndReturn
 */
export type ProgressCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * The data used to create many Progresses.
   */
  data: Prisma.ProgressCreateManyInput | Prisma.ProgressCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Progress update
 */
export type ProgressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * The data needed to update a Progress.
   */
  data: Prisma.XOR<Prisma.ProgressUpdateInput, Prisma.ProgressUncheckedUpdateInput>
  /**
   * Choose, which Progress to update.
   */
  where: Prisma.ProgressWhereUniqueInput
}

/**
 * Progress updateMany
 */
export type ProgressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Progresses.
   */
  data: Prisma.XOR<Prisma.ProgressUpdateManyMutationInput, Prisma.ProgressUncheckedUpdateManyInput>
  /**
   * Filter which Progresses to update
   */
  where?: Prisma.ProgressWhereInput
  /**
   * Limit how many Progresses to update.
   */
  limit?: number
}

/**
 * Progress updateManyAndReturn
 */
export type ProgressUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * The data used to update Progresses.
   */
  data: Prisma.XOR<Prisma.ProgressUpdateManyMutationInput, Prisma.ProgressUncheckedUpdateManyInput>
  /**
   * Filter which Progresses to update
   */
  where?: Prisma.ProgressWhereInput
  /**
   * Limit how many Progresses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Progress upsert
 */
export type ProgressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * The filter to search for the Progress to update in case it exists.
   */
  where: Prisma.ProgressWhereUniqueInput
  /**
   * In case the Progress found by the `where` argument doesn't exist, create a new Progress with this data.
   */
  create: Prisma.XOR<Prisma.ProgressCreateInput, Prisma.ProgressUncheckedCreateInput>
  /**
   * In case the Progress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProgressUpdateInput, Prisma.ProgressUncheckedUpdateInput>
}

/**
 * Progress delete
 */
export type ProgressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
  /**
   * Filter which Progress to delete.
   */
  where: Prisma.ProgressWhereUniqueInput
}

/**
 * Progress deleteMany
 */
export type ProgressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Progresses to delete
   */
  where?: Prisma.ProgressWhereInput
  /**
   * Limit how many Progresses to delete.
   */
  limit?: number
}

/**
 * Progress.clueUsages
 */
export type Progress$clueUsagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClueUsage
   */
  select?: Prisma.ClueUsageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ClueUsage
   */
  omit?: Prisma.ClueUsageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClueUsageInclude<ExtArgs> | null
  where?: Prisma.ClueUsageWhereInput
  orderBy?: Prisma.ClueUsageOrderByWithRelationInput | Prisma.ClueUsageOrderByWithRelationInput[]
  cursor?: Prisma.ClueUsageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ClueUsageScalarFieldEnum | Prisma.ClueUsageScalarFieldEnum[]
}

/**
 * Progress without action
 */
export type ProgressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Progress
   */
  select?: Prisma.ProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Progress
   */
  omit?: Prisma.ProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProgressInclude<ExtArgs> | null
}
