
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  PARTNER: 'PARTNER',
  PLAYER: 'PLAYER'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const HuntStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  FINISHED: 'FINISHED'
} as const

export type HuntStatus = (typeof HuntStatus)[keyof typeof HuntStatus]


export const ParticipationStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED'
} as const

export type ParticipationStatus = (typeof ParticipationStatus)[keyof typeof ParticipationStatus]


export const ProgressStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED'
} as const

export type ProgressStatus = (typeof ProgressStatus)[keyof typeof ProgressStatus]


export const ActionType = {
  GPS: 'GPS',
  QR_CODE: 'QR_CODE',
  AR: 'AR',
  RIDDLE: 'RIDDLE'
} as const

export type ActionType = (typeof ActionType)[keyof typeof ActionType]
