
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  ClueUsage: 'ClueUsage',
  Clue: 'Clue',
  Hunt: 'Hunt',
  Participation: 'Participation',
  Progress: 'Progress',
  Step: 'Step',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ClueUsageScalarFieldEnum = {
  id: 'id',
  usedAt: 'usedAt',
  refProgress: 'refProgress',
  refClue: 'refClue'
} as const

export type ClueUsageScalarFieldEnum = (typeof ClueUsageScalarFieldEnum)[keyof typeof ClueUsageScalarFieldEnum]


export const ClueScalarFieldEnum = {
  id: 'id',
  message: 'message',
  penaltyCost: 'penaltyCost',
  orderNumber: 'orderNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  refStep: 'refStep'
} as const

export type ClueScalarFieldEnum = (typeof ClueScalarFieldEnum)[keyof typeof ClueScalarFieldEnum]


export const HuntScalarFieldEnum = {
  id: 'id',
  title: 'title',
  shortDescription: 'shortDescription',
  description: 'description',
  startDate: 'startDate',
  endDate: 'endDate',
  radius: 'radius',
  coverImage: 'coverImage',
  status: 'status',
  rewardType: 'rewardType',
  rewardValue: 'rewardValue',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  refUser: 'refUser'
} as const

export type HuntScalarFieldEnum = (typeof HuntScalarFieldEnum)[keyof typeof HuntScalarFieldEnum]


export const ParticipationScalarFieldEnum = {
  id: 'id',
  startTime: 'startTime',
  endTime: 'endTime',
  totalPoints: 'totalPoints',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  refUser: 'refUser',
  refHunt: 'refHunt'
} as const

export type ParticipationScalarFieldEnum = (typeof ParticipationScalarFieldEnum)[keyof typeof ParticipationScalarFieldEnum]


export const ProgressScalarFieldEnum = {
  id: 'id',
  statut: 'statut',
  totalPoints: 'totalPoints',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  refParticipation: 'refParticipation',
  refStep: 'refStep'
} as const

export type ProgressScalarFieldEnum = (typeof ProgressScalarFieldEnum)[keyof typeof ProgressScalarFieldEnum]


export const StepScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  title: 'title',
  radius: 'radius',
  actionType: 'actionType',
  arMarkerUrl: 'arMarkerUrl',
  arContent: 'arContent',
  qrCodeValue: 'qrCodeValue',
  points: 'points',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  refHunt: 'refHunt'
} as const

export type StepScalarFieldEnum = (typeof StepScalarFieldEnum)[keyof typeof StepScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  firstname: 'firstname',
  lastname: 'lastname',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  profilePicture: 'profilePicture',
  lastConnection: 'lastConnection',
  country: 'country',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

